PREFIX premis: <http://www.loc.gov/premis/rdf/v1#>
PREFIX test: <info:fedora/test/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ual: <http://terms.library.ualberta.ca/>
PREFIX ualids: <http://terms.library.ualberta.ca/identifiers/>
PREFIX ualid: <http://terms.library.ualberta.ca/id/>
PREFIX ualdate: <http://terms.library.ualberta.ca/date/>
PREFIX ualrole: <http://terms.library.ualberta.ca/role/>
PREFIX ualthesis: <http://terms.library.ualberta.ca/thesis/>
PREFIX info: <info:fedora/fedora-system:def/model#>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX pcdm: <http://pcdm.org/models#>
PREFIX works: <http://projecthydra.org/works/models#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fedora: <http://fedora.info/definitions/v4/repository#>
PREFIX iana: <http://www.iana.org/assignments/relation/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX acl: <http://projecthydra.org/ns/auth/acl#>
PREFIX webacl: <http://www.w3.org/ns/auth/acl#>
PREFIX scholar: <http://scholarsphere.psu.edu/ns#>
PREFIX rels: <info:fedora/fedora-system:def/relations-external#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX mrels: <http://id.loc.gov/vocabulary/relators/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/3.0/>

CONSTRUCT {
	?resource info:hasModel 'IRItem' ;
		fedora:created ?created ;
		fedora:createdBy ?createdBy ;
		fedora:digest ?digest ;
		fedora:exportsAs ?exportsAs ;
		fedora:hasFixityService ?hasFixityService ;
		fedora:hasParent ?hasParent ;
		fedora:hasVersions ?hasVersions ;
		fedora:lastModified ?lastModified ;
		fedora:lastModifiedBy ?lastModifiedBy ;
		fedora:mimeType ?mimeType ;
		fedora:mixinTypes ?mixinTypes ;
		fedora:primaryType ?primaryType ;
		fedora:uuid ?uuid ;
		fedora:writable ?writable ;
		ual:institution ?dgg ;
		ual:dissertant ?dis ;
		ual:depositor ?dpt ;
		ual:supervisor ?ths ;
		acl:embargoHistory ?embargoHistory ;
		acl:embargoReleaseDate ?embargoReleaseDate ;
		acl:hasEmbargo ?hasEmbargo ;
		acl:visibilityAfterEmbargo ?visibilityAfterEmbargo ;
		acl:visibilityDuringEmbargo ?visibilityDuringEmbargo ;
		bibo:degree ?ThesisDegree ;
		scholar:onBehalfOf ?onBehalfOf ;
		scholar:proxyDepositor ?proxyDepositor ;
		scholar:relativePath ?relativePath ;
		ual:parentCommunityId ?belongsToCommunity ;
		ual:fedora3Handle ?fedora3handle ;
		ual:fedora3UUID ?fedora3uuid ;
		ual:graduationDate ?graduationdate ;
		ual:parentCollectionTitle ?hasCollection ;
		pcdm:memberOf ?hasCollectionId ;
		ualids:ingestbatch ?ingestbatch ;
		rdf:type ?is_community ;
		ual:proquest ?proquest ;
		dcterm:alternative ?ser ;
		ual:specialization ?specialization ;
		ual:committeeMember ?thesiscommitteemember ;
		ual:thesisLevel ?thesislevel ;
		dcterm:alternative ?trid ;
		ual:unicorn ?unicorn ;
		ual:parentCommunityId ?belongsToCommunity ;
		ual:graduationDate ?graduationdate ;
		ual:parentCollectionTitle ?hasCollection ;
		pcdm:memberOf ?hasCollectionId ;
		prism:doi ?doi ;
		ual:fedora3Handle ?fedora3handle ;
		ual:fedora3UUID ?fedora3uuid ;
		ual:proquest ?proquest ;
		dcterm:alternative ?ser ;
		dcterm:alternative ?trid ;
		ual:unicorn ?unicorn ;
		rdf:type ?is_community ;
		ual:committeeMember ?thesiscommitteemember ;
		ual:specialization ?specialization ;
		ual:thesisLevel ?thesislevel ;
		ual:department ?AcademicDepartment ;
		iana:describedby ?describedby ;
		iana:describes ?describes ;
		premis:hasOriginalName ?hasOriginalName ;
		premis:hasSize ?hasSize ;
		webacl:accessTo ?accessTo ;
		webacl:agent ?agent ;
		webacl:mode ?mode ;
		info:createdDate ?createdDate ;
		info:downloadFilename ?downloadFilename ;
		pcdm:hasMember ?hasCollectionMember ;
		rels:isPartOf ?isPartOf ;
		dc:format ?format ;
		dc:title ?title ;
		dcterm:abstract ?abstract ;
		dcterm:alternative ?alternative ;
		dc:contributor ?contributor ;
		dcterm:created ?created ;
		dc:creator ?creator ;
		dcterm:date_uploaded ?date_uploaded ;
		dcterm:dateAccepted ?dateAccepted ;
		dcterm:dateSubmitted ?dateSubmitted ;
		dcterm:description ?description ;
		dcterm:identifier ?identifier ;
		dcterm:isVersionOf ?isVersionOf ;
		dcterm:language ?language ;
		dcterm:license ?license ;
		dcterm:modified ?modified ;
		dcterm:publisher ?publisher ;
		dcterm:relation ?relation ;
		dc:rights ?rights ;
		dcterm:source ?source ;
		dcterm:spatial ?spatial ;
		dc:subject ?subject ;
		dcterm:temporal ?temporal ;
		dcterm:title ?title ;
		dcterm:type ?dctype ;
		rdf:type ?rdftype ;
		ual:parentCommunityId ?belongsToCommunity ;
		ual:parentCollectionTitle ?hasCollection ;
		pcdm:memberOf ?hasCollectionId ;
		ual:ingestBatch ?ingestbatch ;
		rdf:type ?is_community ;
}
WHERE {
	?resource info:hasModel 'GenericFile'^^xsd:string .
		OPTIONAL { ?resource fedora:created ?created } .
		OPTIONAL { ?resource fedora:createdBy ?createdBy } .
		OPTIONAL { ?resource fedora:digest ?digest } .
		OPTIONAL { ?resource fedora:exportsAs ?exportsAs } .
		OPTIONAL { ?resource fedora:hasFixityService ?hasFixityService } .
		OPTIONAL { ?resource fedora:hasParent ?hasParent } .
		OPTIONAL { ?resource fedora:hasVersions ?hasVersions } .
		OPTIONAL { ?resource fedora:lastModified ?lastModified } .
		OPTIONAL { ?resource fedora:lastModifiedBy ?lastModifiedBy } .
		OPTIONAL { ?resource fedora:mimeType ?mimeType } .
		OPTIONAL { ?resource fedora:mixinTypes ?mixinTypes } .
		OPTIONAL { ?resource fedora:primaryType ?primaryType } .
		OPTIONAL { ?resource fedora:uuid ?uuid } .
		OPTIONAL { ?resource fedora:writable ?writable } .
		OPTIONAL { ?resource mrels:dgg ?dgg } .
		OPTIONAL { ?resource mrels:dis ?dis } .
		OPTIONAL { ?resource mrels:dpt ?dpt } .
		OPTIONAL { ?resource mrels:ths ?ths } .
		OPTIONAL { ?resource acl:embargoHistory ?embargoHistory } .
		OPTIONAL { ?resource acl:embargoReleaseDate ?embargoReleaseDate } .
		OPTIONAL { ?resource acl:hasEmbargo ?hasEmbargo } .
		OPTIONAL { ?resource acl:visibilityAfterEmbargo ?visibilityAfterEmbargo } .
		OPTIONAL { ?resource acl:visibilityDuringEmbargo ?visibilityDuringEmbargo } .
		OPTIONAL { ?resource bibo:ThesisDegree ?ThesisDegree } .
		OPTIONAL { ?resource scholar:onBehalfOf ?onBehalfOf } .
		OPTIONAL { ?resource scholar:proxyDepositor ?proxyDepositor } .
		OPTIONAL { ?resource scholar:relativePath ?relativePath } .
		OPTIONAL { ?resource ualids:belongsToCommunity ?belongsToCommunity } .
		OPTIONAL { ?resource ualids:fedora3handle ?fedora3handle } .
		OPTIONAL { ?resource ualids:fedora3uuid ?fedora3uuid } .
		OPTIONAL { ?resource ualids:graduationdate ?graduationdate } .
		OPTIONAL { ?resource ualids:hasCollection ?hasCollection } .
		OPTIONAL { ?resource ualids:hasCollectionId ?hasCollectionId } .
		OPTIONAL { ?resource ualids:ingestbatch ?ingestbatch } .
		OPTIONAL { ?resource ualids:is_community ?is_community } .
		OPTIONAL { ?resource ualids:proquest ?proquest } .
		OPTIONAL { ?resource ualids:ser ?ser } .
		OPTIONAL { ?resource ualids:specialization ?specialization } .
		OPTIONAL { ?resource ualids:thesiscommitteemember ?thesiscommitteemember } .
		OPTIONAL { ?resource ualids:thesislevel ?thesislevel } .
		OPTIONAL { ?resource ualids:trid ?trid } .
		OPTIONAL { ?resource ualids:unicorn ?unicorn } .
		OPTIONAL { ?resource ual:belongsToCommunity ?belongsToCommunity } .
		OPTIONAL { ?resource ualdate:graduationdate ?graduationdate } .
		OPTIONAL { ?resource ual:hasCollection ?hasCollection } .
		OPTIONAL { ?resource ual:hasCollectionId ?hasCollectionId } .
		OPTIONAL { ?resource ualid:doi ?doi } .
		OPTIONAL { ?resource ualid:fedora3handle ?fedora3handle } .
		OPTIONAL { ?resource ualid:fedora3uuid ?fedora3uuid } .
		OPTIONAL { ?resource ualid:proquest ?proquest } .
		OPTIONAL { ?resource ualid:ser ?ser } .
		OPTIONAL { ?resource ualid:trid ?trid } .
		OPTIONAL { ?resource ualid:unicorn ?unicorn } .
  		OPTIONAL { ?resource ualid:hasCollection ?hasCollection } .
		OPTIONAL { ?resource ualid:hasCollectionId ?hasCollectionId } .
		OPTIONAL { ?resource ualid:ingestbatch ?ingestbatch } .
		OPTIONAL { ?resource ualid:is_community ?is_community } .
		OPTIONAL { ?resource ual:is_community ?is_community } .
		OPTIONAL { ?resource ualrole:thesiscommitteemember ?thesiscommitteemember } .
		OPTIONAL { ?resource ualthesis:specialization ?specialization } .
		OPTIONAL { ?resource ualthesis:thesislevel ?thesislevel } .
		OPTIONAL { ?resource bibo:AcademicDepartment ?AcademicDepartment } .
		OPTIONAL { ?resource iana:describedby ?describedby } .
		OPTIONAL { ?resource iana:describes ?describes } .
		OPTIONAL { ?resource premis:hasOriginalName ?hasOriginalName } .
		OPTIONAL { ?resource premis:hasSize ?hasSize } .
		OPTIONAL { ?resource webacl:accessTo ?accessTo } .
		OPTIONAL { ?resource webacl:agent ?agent } .
		OPTIONAL { ?resource webacl:mode ?mode } .
		OPTIONAL { ?resource info:createdDate ?createdDate } .
		OPTIONAL { ?resource info:downloadFilename ?downloadFilename } .
		OPTIONAL { ?resource rels:hasCollectionMember ?hasCollectionMember } .
		OPTIONAL { ?resource rels:isPartOf ?isPartOf } .
		OPTIONAL { ?resource dc:format ?format } .
		OPTIONAL { ?resource dc:title ?title } .
		OPTIONAL { ?resource dcterm:abstract ?abstract } .
		OPTIONAL { ?resource dcterm:alternative ?alternative } .
		OPTIONAL { ?resource dcterm:contributor ?contributor } .
		OPTIONAL { ?resource dcterm:created ?created } .
		OPTIONAL { ?resource dcterm:creator ?creator } .
		OPTIONAL { ?resource dcterm:date_uploaded ?date_uploaded } .
		OPTIONAL { ?resource dcterm:dateAccepted ?dateAccepted } .
		OPTIONAL { ?resource dcterm:dateSubmitted ?dateSubmitted } .
		OPTIONAL { ?resource dcterm:description ?description } .
		OPTIONAL { ?resource dcterm:identifier ?identifier } .
		OPTIONAL { ?resource dcterm:isVersionOf ?isVersionOf } .
		OPTIONAL { ?resource dcterm:language ?language } .
		OPTIONAL { ?resource dcterm:license ?license } .
		OPTIONAL { ?resource dcterm:modified ?modified } .
		OPTIONAL { ?resource dcterm:publisher ?publisher } .
		OPTIONAL { ?resource dcterm:relation ?relation } .
		OPTIONAL { ?resource dcterm:rights ?rights } .
		OPTIONAL { ?resource dcterm:source ?source } .
		OPTIONAL { ?resource dcterm:spatial ?spatial } .
		OPTIONAL { ?resource dcterm:subject ?subject } .
		OPTIONAL { ?resource dcterm:temporal ?temporal } .
		OPTIONAL { ?resource dcterm:title ?title } .
		OPTIONAL { ?resource dcterm:type ?dctype } .
		OPTIONAL { ?resource rdf:type ?rdftype } .
		OPTIONAL { ?resource ualid:belongsToCommunity ?belongsToCommunity } .

}