subjects = [{"useForm":"regret minimization",
"mappings": ["regret minimalization"]},
{"useForm":"abstractions",
"mappings": ["abstraction","abstraction."]},
{"useForm":"simulations",
"mappings": ["simulation"]},
{"useForm":"database",
"mappings": ["databases"]},
{"useForm":"non-newtonian fluid",
"mappings": ["non-newtonian fluids"]},
{"useForm":"programming environments",
"mappings": ["programming environment"]},
{"useForm":"color histograms",
"mappings": ["color hisotgrams"]},
{"useForm":"privacy preserving clustering",
"mappings": ["privacy-preserving clustering"]},
{"useForm":"phylogenic root",
"mappings": ["phylogenetic root"]},
{"useForm":"compiler",
"mappings": ["compilers"]},
{"useForm":"boreal forest",
"mappings": ["boreal forests"]},
{"useForm":"service",
"mappings": ["services"]},
{"useForm":"alzheimer's disease",
"mappings": ["alzheimer disease","alzheimer’s disease","alzheimer disease."]},
{"useForm":"intervention",
"mappings": ["interventions"]},
{"useForm":"pore pressures",
"mappings": ["pore pressure"]},
{"useForm":"interaction",
"mappings": ["interactions"]},
{"useForm":"cohesionless soils",
"mappings": ["cohesionless soil"]},
{"useForm":"numerical modelling",
"mappings": ["numerical modeling"]},
{"useForm":"shear zone",
"mappings": ["shear zones"]},
{"useForm":"field",
"mappings": ["fields"]},
{"useForm":"load tests",
"mappings": ["load test"]},
{"useForm":"landslide",
"mappings": ["landslides","landslides."]},
{"useForm":"british columbia",
"mappings": ["british-columbia"]},
{"useForm":"modelling",
"mappings": ["modeling"]},
{"useForm":"geogrid",
"mappings": ["geogrids"]},
{"useForm":"rocky mountains",
"mappings": ["rocky-mountains"]},
{"useForm":"oil sands",
"mappings": ["oilsands"]},
{"useForm":"settlements",
"mappings": ["settlement"]},
{"useForm":"decision making",
"mappings": ["decision-making"]},
{"useForm":"spatial variablity",
"mappings": ["spatial variability"]},
{"useForm":"root-growth",
"mappings": ["root growth"]},
{"useForm":"aspen forest",
"mappings": ["aspen forests"]},
{"useForm":"wildfires",
"mappings": ["wildfire"]},
{"useForm":"spatial scale",
"mappings": ["spatial scales"]},
{"useForm":"climate-change",
"mappings": ["climate change"]},
{"useForm":"emissions",
"mappings": ["emission"]},
{"useForm":"methylmercury",
"mappings": ["methyl mercury"]},
{"useForm":"peatland",
"mappings": ["peatlands"]},
{"useForm":"carbon-dioxide exchange",
"mappings": ["carbon dioxide exchange"]},
{"useForm":"plant-communities",
"mappings": ["plant communities"]},
{"useForm":"mechanism",
"mappings": ["mechanisms"]},
{"useForm":"element",
"mappings": ["elements"]},
{"useForm":"northern-hemisphere",
"mappings": ["northern hemisphere"]},
{"useForm":"eastern canada",
"mappings": ["western canada"]},
{"useForm":"insects",
"mappings": ["insect"]},
{"useForm":"soil-moisture",
"mappings": ["soil moisture"]},
{"useForm":"scale",
"mappings": ["scales"]},
{"useForm":"point counts",
"mappings": ["point count"]},
{"useForm":"species distributions",
"mappings": ["species distribution"]},
{"useForm":"systematic reviews",
"mappings": ["systematic review"]},
{"useForm":"job satisfaction",
"mappings": ["job-satisfaction"]},
{"useForm":"verification",
"mappings": ["versification"]},
{"useForm":"disease",
"mappings": ["diseases"]},
{"useForm":"association",
"mappings": ["associations"]},
{"useForm":"revacularization",
"mappings": ["revascularization"]},
{"useForm":"canada",
"mappings": ["canada,"]},
{"useForm":"ionic strength",
"mappings": ["ionic-strength"]},
{"useForm":"steric model",
"mappings": ["steric mode"]},
{"useForm":"naphthenic acids",
"mappings": ["naphthenic acid"]},
{"useForm":"organic-compounds",
"mappings": ["inorganic-compounds"]},
{"useForm":"zeolites",
"mappings": ["zeolite"]},
{"useForm":"separations",
"mappings": ["separation"]},
{"useForm":"rnaseq",
"mappings": ["rna-seq"]},
{"useForm":"aqueous-solutions",
"mappings": ["aqueous-solution"]},
{"useForm":"water-treatment",
"mappings": ["water treatment"]},
{"useForm":"systems",
"mappings": ["system"]},
{"useForm":"hydroxyl radical",
"mappings": ["hydroxyl radicals"]},
{"useForm":"mass-spectrometry",
"mappings": ["mass spectrometry","mass spectromentry","mass spectrometry."]},
{"useForm":"receptors",
"mappings": ["preceptors"]},
{"useForm":"immunizaton",
"mappings": ["immunization"]},
{"useForm":"long term care",
"mappings": ["long-term care"]},
{"useForm":"cardiac surgery",
"mappings": ["cardiac-surgery"]},
{"useForm":"clinical practice",
"mappings": ["clinical-practice"]},
{"useForm":"health care",
"mappings": ["health-care"]},
{"useForm":"mixed methods",
"mappings": ["mixed method"]},
{"useForm":"evidence based medicine",
"mappings": ["evidence-based medicine"]},
{"useForm":"united states",
"mappings": ["united-states"]},
{"useForm":"infections",
"mappings": ["infection"]},
{"useForm":"trial",
"mappings": ["trials"]},
{"useForm":"organizations",
"mappings": ["organization"]},
{"useForm":"conceptual-framework",
"mappings": ["conceptual framework"]},
{"useForm":"crop yields",
"mappings": ["crop yield"]},
{"useForm":"tissues",
"mappings": ["tissue"]},
{"useForm":"positive interactions",
"mappings": ["positive interaction"]},
{"useForm":"red squirrels",
"mappings": ["red squirrel"]},
{"useForm":"bacillus thuringiensis",
"mappings": ["bacillus-thuringiensis"]},
{"useForm":"population-genetics",
"mappings": ["population genetics"]},
{"useForm":"ultraviolet-radiation",
"mappings": ["ultraviolet radiation"]},
{"useForm":"aerosol",
"mappings": ["aerosols"]},
{"useForm":"cystic fibrosi",
"mappings": ["cystic fibrosis"]},
{"useForm":"protein-kinase",
"mappings": ["protein-kinase-c","protein kinase a"]},
{"useForm":"plant",
"mappings": ["plants"]},
{"useForm":"populus-tremuloides",
"mappings": ["populus tremuloides"]},
{"useForm":"mountain pine beetle",
"mappings": ["mountain pine-beetle"]},
{"useForm":"dendroctonus ponderoae",
"mappings": ["dendroctonus ponderosae","dendroctonus-ponderosae"]},
{"useForm":"seed banks",
"mappings": ["seed bank"]},
{"useForm":"resource management",
"mappings": ["resource-management"]},
{"useForm":"ungulates",
"mappings": ["ungulate"]},
{"useForm":"forest fire",
"mappings": ["forest fires"]},
{"useForm":"carbon dioxide",
"mappings": ["carbon-dioxide"]},
{"useForm":"forests",
"mappings": ["forest"]},
{"useForm":"communication",
"mappings": ["communications"]},
{"useForm":"nursing home",
"mappings": ["nursing homes","nursing-homes"]},
{"useForm":"framework",
"mappings": ["frameworks"]},
{"useForm":"evidence-based practice",
"mappings": ["evidence based practice"]},
{"useForm":"behavior",
"mappings": ["behaviors","behaviour"]},
{"useForm":"randomized-control trials",
"mappings": ["randomized control trials"]},
{"useForm":"randomized controlled trial",
"mappings": ["randomized controlled trials"]},
{"useForm":"patient",
"mappings": ["patients"]},
{"useForm":"surveys",
"mappings": ["survey"]},
{"useForm":"program",
"mappings": ["programs"]},
{"useForm":"genetic correlation",
"mappings": ["genetic correlations"]},
{"useForm":"maternal effect",
"mappings": ["maternal effects"]},
{"useForm":"color",
"mappings": ["colors"]},
{"useForm":"flight",
"mappings": ["light"]},
{"useForm":"allee effects",
"mappings": ["allee effect"]},
{"useForm":"invasions",
"mappings": ["invasion"]},
{"useForm":"cervus elaphus",
"mappings": ["cervus elephus"]},
{"useForm":"migration",
"mappings": ["emigration"]},
{"useForm":"selection",
"mappings": [" selection"]},
{"useForm":"jack pine forests",
"mappings": ["jack pine forest"]},
{"useForm":"carassius-carassius",
"mappings": ["carassius carassius"]},
{"useForm":"density dependence",
"mappings": ["density-dependence"]},
{"useForm":"population dynamics",
"mappings": ["population-dynamics"]},
{"useForm":"models",
"mappings": ["model"]},
{"useForm":"patterns",
"mappings": ["pattern"]},
{"useForm":"streams",
"mappings": ["stream"]},
{"useForm":"productivity",
"mappings": ["productivitiy"]},
{"useForm":"escherichia-coli",
"mappings": ["escherichia coli"]},
{"useForm":"saccharomyces-cerevisiae",
"mappings": ["saccharomyces cerevisiae","saccharomyces cerevisiae."]},
{"useForm":"arabidopsis-thaliana",
"mappings": ["arabidopsis thaliana"]},
{"useForm":"theropoda",
"mappings": ["theropod"]},
{"useForm":"oil sands process-affected water",
"mappings": ["oil sands process affected water"]},
{"useForm":"rate constants",
"mappings": ["ate constants"]},
{"useForm":"intentions",
"mappings": ["intention"]},
{"useForm":"weight change",
"mappings": ["weight changes"]},
{"useForm":"built environment",
"mappings": ["built environment "]},
{"useForm":"environment",
"mappings": ["environments"]},
{"useForm":"nanoparticles",
"mappings": ["nanoparticle"]},
{"useForm":"human-immunodeficiency-virus",
"mappings": ["human immunodeficiency virus"]},
{"useForm":"prediction",
"mappings": ["predictions"]},
{"useForm":"in-vitro",
"mappings": ["invitro"]},
{"useForm":"drug delivery",
"mappings": ["drug-delivery"]},
{"useForm":"gravity models",
"mappings": ["gravity model"]},
{"useForm":"asphaltene",
"mappings": ["asphaltenes"]},
{"useForm":"sea lice",
"mappings": ["sea ice"]},
{"useForm":"health",
"mappings": ["healthy"]},
{"useForm":"risk factors",
"mappings": ["risk-factors"]},
{"useForm":"healthcare aides",
"mappings": ["health care aides"]},
{"useForm":"aging",
"mappings": ["ageing"]},
{"useForm":"northern ireland",
"mappings": ["northern-ireland"]},
{"useForm":"impacts",
"mappings": ["impact"]},
{"useForm":"ecosystems",
"mappings": ["ecosystem"]},
{"useForm":"landscapes",
"mappings": ["landscape"]},
{"useForm":"field pea",
"mappings": ["field peas"]},
{"useForm":"grizzly bear",
"mappings": ["grizzly bears"]},
{"useForm":"cardiovascular disease",
"mappings": ["cardiovascular diseases"]},
{"useForm":"innovation",
"mappings": ["innovations"]},
{"useForm":"hospitals",
"mappings": ["hospital"]},
{"useForm":"māori masculinity",
"mappings": ["maori masculinity"]},
{"useForm":"oil sands tailings ponds",
"mappings": ["oil sands tailings pond"]},
{"useForm":"diversity",
"mappings": ["diversity "]},
{"useForm":"adults",
"mappings": ["adult"]},
{"useForm":"law of the iterated logarithm",
"mappings": ["laws of the iterated logarithm"]},
{"useForm":"cytokines",
"mappings": ["cytokine"]},
{"useForm":"india",
"mappings": ["indica"]},
{"useForm":"wetland",
"mappings": ["wetlands"]},
{"useForm":"dinosaurs",
"mappings": ["dinosaur"]},
{"useForm":"populations",
"mappings": ["population"]},
{"useForm":"meta-analysis",
"mappings": ["metaanalysis"]},
{"useForm":"assessement",
"mappings": ["assessment"]},
{"useForm":"seed-transfer guidelines",
"mappings": ["seed transfer guidelines"]},
{"useForm":"variance-components",
"mappings": ["variance components"]},
{"useForm":"national-park",
"mappings": ["national park"]},
{"useForm":"genetic variation",
"mappings": ["genetic-variation"]},
{"useForm":"evolution",
"mappings": [" evolution"]},
{"useForm":"lightening",
"mappings": ["lightning"]},
{"useForm":"trace-elements",
"mappings": ["trace-element"]},
{"useForm":"correlations",
"mappings": ["correlation"]},
{"useForm":"water quality",
"mappings": ["water-quality"]},
{"useForm":"childcare",
"mappings": ["child care"]},
{"useForm":"interdisciplinarity",
"mappings": ["interdisciplinary"]},
{"useForm":"method",
"mappings": ["methods"]},
{"useForm":"disciplines",
"mappings": ["discipline"]},
{"useForm":"sequence",
"mappings": ["sequences"]},
{"useForm":"transitions",
"mappings": ["transition"]},
{"useForm":"masting",
"mappings": ["mating"]},
{"useForm":"grassland",
"mappings": ["grasslands"]},
{"useForm":"polar bears",
"mappings": ["polar bear"]},
{"useForm":"lodgepole pine",
"mappings": ["lodge-pole pine"]},
{"useForm":"metaphors",
"mappings": ["metaphor"]},
{"useForm":"mathematical-model",
"mappings": ["mathematical models","mathematical model"]},
{"useForm":"semi-variogram",
"mappings": ["semivariogram"]},
{"useForm":"membrane",
"mappings": ["membranes"]},
{"useForm":"maximum-likelihood",
"mappings": [" maximum-likelihood","maximum likelihood"]},
{"useForm":"sp-nov",
"mappings": ["sp-nov."]},
{"useForm":"choristoneura rosaceana",
"mappings": ["choristoneura-rosaceana","chroristoneura rosaceana"]},
{"useForm":"gene-expression",
"mappings": ["gene expression","gene expression "]},
{"useForm":"soil amendment",
"mappings": ["soil amendments"]},
{"useForm":"genetic structure",
"mappings": ["genetic-structure"]},
{"useForm":"grosmanniaclavigera",
"mappings": ["grosmannia-clavigera","grosmannia clavigera","grosmannia clavigera "]},
{"useForm":"genetics",
"mappings": ["genetic"]},
{"useForm":"aluminum tolerance",
"mappings": ["aluminum-tolerance"]},
{"useForm":"nutrient solutions",
"mappings": ["nutrient solution"]},
{"useForm":"mechanistic models",
"mappings": ["mechanistic model"]},
{"useForm":"step selection functions",
"mappings": ["step selection function"]},
{"useForm":"random regression model",
"mappings": ["random regression-models"]},
{"useForm":"proteins",
"mappings": ["protein"]},
{"useForm":"expressions",
"mappings": ["expression"]},
{"useForm":"mitochondrial dna",
"mappings": ["mitochondrial-dna"]},
{"useForm":"social interactions",
"mappings": ["social interaction"]},
{"useForm":"spatial patterns",
"mappings": ["spatial pattern"]},
{"useForm":"resources",
"mappings": ["resource"]},
{"useForm":"updates",
"mappings": ["update"]},
{"useForm":"genomes",
"mappings": ["genomes "]},
{"useForm":"neurospora-crassa",
"mappings": ["neurospora crassa"]},
{"useForm":"cell biology ",
"mappings": ["cell biology"]},
{"useForm":"maternity-care experiences",
"mappings": ["maternity care experiences"]},
{"useForm":"narrative systhesis",
"mappings": ["narrative synthesis"]},
{"useForm":"phototropism",
"mappings": ["phototropism "]},
{"useForm":"handed behavior",
"mappings": ["handed behaviour"]},
{"useForm":"generations",
"mappings": ["generation"]},
{"useForm":"nursing students",
"mappings": ["nursing student"]},
{"useForm":"capacity-building",
"mappings": ["capacity building"]},
{"useForm":"postcolonialism",
"mappings": ["postcolonialisme"]},
{"useForm":"health care practice",
"mappings": ["health care practices"]},
{"useForm":"genetic-parameters",
"mappings": ["genetic parameters","genetic parameter"]},
{"useForm":"ixodid ticks",
"mappings": ["ixodid tick"]},
{"useForm":"employer",
"mappings": ["employers"]},
{"useForm":"construction",
"mappings": ["constructions"]},
{"useForm":"genetic diversity",
"mappings": ["genetic diversity "]},
{"useForm":"rainbow-trout",
"mappings": ["rainbow trout"]},
{"useForm":"problem based learning",
"mappings": ["problem-based learning"]},
{"useForm":"linkage disequilibrium",
"mappings": [" linkage disequilibrium"]},
{"useForm":"effective population-size",
"mappings": ["effective population size"]},
{"useForm":"fatty acids",
"mappings": ["fatty acid"]},
{"useForm":"beef cattle",
"mappings": ["beef-cattle"]},
{"useForm":"parasites",
"mappings": ["parasite"]},
{"useForm":"messenger-rna",
"mappings": [" messenger-rna"]},
{"useForm":"instruments",
"mappings": ["instrument"]},
{"useForm":"songbirds",
"mappings": ["songbird"]},
{"useForm":"tree ring widths",
"mappings": ["tree ring width"]},
{"useForm":"podocarpaceae",
"mappings": ["podocarpaceaew"]},
{"useForm":"beef cows",
"mappings": ["beef cow"]},
{"useForm":"birthweight",
"mappings": ["birth weight"]},
{"useForm":"annotation",
"mappings": ["annotation "]},
{"useForm":"draft sequence",
"mappings": ["draft sequences"]},
{"useForm":"japonica;",
"mappings": ["japonica"]},
{"useForm":"risk assessement",
"mappings": ["risk assessment","risk assessment."]},
{"useForm":"natural resources",
"mappings": ["natural sources"]},
{"useForm":"coyote",
"mappings": ["coyotes"]},
{"useForm":"adaptation",
"mappings": ["adaptations"]},
{"useForm":"radio telemetry",
"mappings": ["radiotelemetry"]},
{"useForm":"spectrum",
"mappings": [" spectrum"]},
{"useForm":"strain",
"mappings": ["strains"]},
{"useForm":"maize",
"mappings": [" maize"]},
{"useForm":"sex-chromosomes",
"mappings": ["sex chromosomes"]},
{"useForm":"refuges",
"mappings": ["refugees"]},
{"useForm":"indicator",
"mappings": ["indicators"]},
{"useForm":"natural-selection",
"mappings": ["natural selection"]},
{"useForm":"fruit development",
"mappings": ["fruit development,"]},
{"useForm":"movements",
"mappings": ["movement"]},
{"useForm":"molecular-dynamics",
"mappings": ["molecular dynamics"]},
{"useForm":"vertebrate",
"mappings": ["vertebrates"]},
{"useForm":"linked-immunosorbent-assay",
"mappings": ["linked immunosorbent-assay"]},
{"useForm":"mutualism",
"mappings": ["mutualisms"]},
{"useForm":"pathogens",
"mappings": ["pathogen"]},
{"useForm":"surface-plasmon resonance",
"mappings": ["surface plasmon resonances"]},
{"useForm":"boreal mixedwood forest",
"mappings": ["boreal mixed-wood forest"]},
{"useForm":"critical domain size",
"mappings": ["critical domain-size"]},
{"useForm":"malacosoma disstria",
"mappings": ["malacosoma-disstria"]},
{"useForm":"parasitoid",
"mappings": ["parasitoids"]},
{"useForm":"tachycineta bicolor",
"mappings": ["tachyncineta bicolor"]},
{"useForm":"tree swallow",
"mappings": ["tree swallows"]},
{"useForm":"genome sequences",
"mappings": ["genome sequence"]},
{"useForm":"transcriptomics",
"mappings": ["transcriptomic"]},
{"useForm":"pathways",
"mappings": ["pathway"]},
{"useForm":"transcriptomes",
"mappings": ["transcriptome"]},
{"useForm":"viridiplantae",
"mappings": ["viridplantae"]},
{"useForm":"visitation effects",
"mappings": ["visitation effect"]},
{"useForm":"outbreak",
"mappings": ["outbreaks"]},
{"useForm":"mutations",
"mappings": ["mutation"]},
{"useForm":"substitution",
"mappings": ["substitutions"]},
{"useForm":"single-nucleotide polymorphisms",
"mappings": ["single nucleotide polymorphisms"]},
{"useForm":"eating behaviour",
"mappings": ["eating behavior"]},
{"useForm":"skeletal muscles",
"mappings": ["skeletal muscle"]},
{"useForm":"legumes",
"mappings": ["legume"]},
{"useForm":"healthcare system",
"mappings": ["health care systems","health care system"]},
{"useForm":"muscle",
"mappings": ["muscles"]},
{"useForm":"contracts law",
"mappings": ["contract law"]},
{"useForm":"governments",
"mappings": ["government"]},
{"useForm":"broiler chickens",
"mappings": ["broiler chicken"]},
{"useForm":"chromosome",
"mappings": ["chromosomes"]},
{"useForm":"arabidopsis",
"mappings": [" arabidopsis"]},
{"useForm":"soil environments",
"mappings": ["soil environment"]},
{"useForm":"lactate-dehydrogenase",
"mappings": ["lactate dehydrogenase"]},
{"useForm":"terpene synthase",
"mappings": ["terpene synthases"]},
{"useForm":"abscisic-acid",
"mappings": ["abscisic acid"]},
{"useForm":"fossil fern",
"mappings": ["fossil ferns"]},
{"useForm":"black-capped chickadees",
"mappings": ["black-capped chickadee"]},
{"useForm":"haplotypes",
"mappings": ["haplotype"]},
{"useForm":"alleles",
"mappings": ["allele"]},
{"useForm":"feeding behaviour",
"mappings": ["feeding behavior","feeding-behavior"]},
{"useForm":"posttraumatic-stress-disorder",
"mappings": ["post-traumatic stress disorder"]},
{"useForm":"particle filter",
"mappings": ["particle filters"]},
{"useForm":"aroids",
"mappings": ["aroid"]},
{"useForm":"body composition",
"mappings": ["body-composition"]},
{"useForm":"soil temperature",
"mappings": ["soil-temperature"]},
{"useForm":"influenza",
"mappings": ["influenz"]},
{"useForm":"binding",
"mappings": ["binding;"]},
{"useForm":"immune response",
"mappings": ["immune responses","immune-responses"]},
{"useForm":"alcohol-dehydrogenase",
"mappings": ["alcohol dehydrogenase"]},
{"useForm":"plasmid",
"mappings": ["plasmids"]},
{"useForm":"seiurus-aurocapillus",
"mappings": ["seiurus aurocapillus"]},
{"useForm":"dna-sequence",
"mappings": ["dna-sequences"]},
{"useForm":"generation;",
"mappings": ["generation"]},
{"useForm":"loblolly pine",
"mappings": ["loblolly-pine"]},
{"useForm":"medications",
"mappings": ["medication"]},
{"useForm":" divergence times",
"mappings": ["divergence times"]},
{"useForm":" phylogenetic analyses",
"mappings": ["phylogenetic analyses"]},
{"useForm":"polymorphisms",
"mappings": ["polymorphism"]},
{"useForm":"alpine meadow",
"mappings": ["alpine meadows"]},
{"useForm":"segmentation;",
"mappings": ["segmentation"]},
{"useForm":"phylogenetics",
"mappings": ["phylogenetics."," phylogenetics"]},
{"useForm":"healthcare providers",
"mappings": ["health care providers"]},
{"useForm":"spreading speeds",
"mappings": ["spreading speed"]},
{"useForm":"salmonids",
"mappings": ["salmonid"]},
{"useForm":"shoot",
"mappings": ["shoots"]},
{"useForm":"salivary gland",
"mappings": ["salivary glands"]},
{"useForm":"principal components analysis",
"mappings": ["principal component analysis"]},
{"useForm":"cooking",
"mappings": ["coking"]},
{"useForm":"candidate gene",
"mappings": ["candidate genes"]},
{"useForm":"peat-mineral mix",
"mappings": ["peat mineral mix"]},
{"useForm":"hybrid vigor",
"mappings": ["hybrid vigour"]},
{"useForm":"next-generation sequencing",
"mappings": ["next generation sequencing"]},
{"useForm":"nucleotide-sequence",
"mappings": ["nucleotide sequence","nucleotide-sequences"]},
{"useForm":"national parks",
"mappings": ["national park"]},
{"useForm":"field experiment",
"mappings": ["field experiments"]},
{"useForm":"growth implants",
"mappings": ["growth implant"]},
{"useForm":"intermediate host",
"mappings": ["intermediate hosts"]},
{"useForm":"double muscling",
"mappings": ["double-muscling"]},
{"useForm":"cones",
"mappings": ["clones"]},
{"useForm":"editorial",
"mappings": ["editorials"]},
{"useForm":"regulator",
"mappings": ["regulators"]},
{"useForm":"production systems",
"mappings": ["production system"]},
{"useForm":"nonindigenous species",
"mappings": ["non-indigenous species"]},
{"useForm":"proteomes",
"mappings": ["proteome"]},
{"useForm":"transcriptome analysis ",
"mappings": ["transcriptome analysis"]},
{"useForm":"ecotones",
"mappings": ["ecotone"]},
{"useForm":"genomewide association study",
"mappings": ["genome-wide association study"]},
{"useForm":"beef heifers",
"mappings": ["beef heifer"]},
{"useForm":"gene-expression profiles",
"mappings": ["gene expression profile"]},
{"useForm":"skeletal-muscle",
"mappings": ["skeletal muscle"]},
{"useForm":"rna sequencing",
"mappings": ["dna sequencing"]},
{"useForm":"mitochondrial genome",
"mappings": [" mitochondrial genome"]},
{"useForm":"nadh dehydrogenase",
"mappings": [" nadh dehydrogenase"]},
{"useForm":"oncidium gower ramsey",
"mappings": [" oncidium gower ramsey"]},
{"useForm":"photosystem-i",
"mappings": [" photosystem-i"]},
{"useForm":"book review",
"mappings": ["book reviews"]},
{"useForm":"stage structure",
"mappings": ["age structure"]},
{"useForm":"characterisation",
"mappings": ["characterization"]},
{"useForm":"large deviations principle",
"mappings": ["large deviation principle"]},
{"useForm":"academic librarians",
"mappings": ["academic librarianship"]},
{"useForm":"alberta legislative assembly--periodicals",
"mappings": ["alberta. legislative assembly-- periodicals"]},
{"useForm":"bibliography national--great britain--periodicals",
"mappings": ["bibliography, nationa--great britain--periodicals","bibliography, national--great britain—periodicals"]},
{"useForm":"great britain--imprints--periodicals",
"mappings": ["great britain--imprints—periodicals","great britain--imprint--periodicals"]},
{"useForm":"toronto stock exchange--periodicals",
"mappings": ["toronto stock exchange—periodicals","toronto stock exchange-- periodicals"]},
{"useForm":"tsx venture exchange--periodicals",
"mappings": ["tsx venture exchange—periodicals", "tsx venture exchange-- periodicals"]},
{"useForm":"statistics",
"mappings": ["statistics."]},
{"useForm":"tar sands",
"mappings": ["tarsands"]},
{"useForm":"workshops",
"mappings": ["workshop"]},
{"useForm":"finance--canada--periodicals",
"mappings": ["finance--canada—periodicals"]},
{"useForm":"needs assessment",
"mappings": ["needs assesment"]},
{"useForm":"narrative",
"mappings": ["narratives"]},
{"useForm":"re-entry",
"mappings": ["reentry"]},
{"useForm":"white spruce",
"mappings": ["whie spruce"]},
{"useForm":"ethane",
"mappings": ["methane","methane."]},
{"useForm":"economics",
"mappings": ["economic"]},
{"useForm":"organic",
"mappings": ["organics"]},
{"useForm":"unemployment--statistics",
"mappings": ["unemloyment--statistics"]},
{"useForm":"diplomats--ontario--ottawa--newspapers",
"mappings": ["diplomates--ontario--ottawa--newspapers"]},
{"useForm":"international relations--newspapers",
"mappings": ["international relations—newspapers","international relations-- newspapers"]},
{"useForm":"stock exchanges--canada--tables--periodicals",
"mappings": ["stock exchanges--canada--tables—periodicals","stock exchange--canada--tables--periodicals"]},
{"useForm":"community informatics",
"mappings": ["community informatics "]},
{"useForm":"evaluation",
"mappings": ["valuation"]},
{"useForm":"humor",
"mappings": ["humour"]},
{"useForm":"teacher",
"mappings": ["teachers"]},
{"useForm":"healthcare",
"mappings": ["health-care","health care"]},
{"useForm":"andragogy",
"mappings": ["adragogy"]},
{"useForm":"canada--politics and government--periodicals",
"mappings": ["canada--politics and government—periodicals","canada--politics and government --periodicals","canada—politics and government—periodicals"]},
{"useForm":"diplomatic and consular service--canada--newspapers",
"mappings": ["diplomatic and consular service—canada—newspapers"]},
{"useForm":"acquired brain injury",
"mappings": ["aquired brain injury"]},
{"useForm":"social network",
"mappings": ["social networks","social networks."]},
{"useForm":"children",
"mappings": ["children "]},
{"useForm":"social service--planning",
"mappings": ["social services--planning"]},
{"useForm":"water management",
"mappings": ["waste management"]},
{"useForm":"cererbral palsy",
"mappings": ["cerebral palsy","cerbral palsy"]},
{"useForm":"feedback processes",
"mappings": ["feedback process"]},
{"useForm":"school of library and information studies (slis)",
"mappings": ["school of library and information studies (slis) "]},
{"useForm":"inventory",
"mappings": ["inventor"]},
{"useForm":"small mammals",
"mappings": ["small mammal"]},
{"useForm":"libraries",
"mappings": ["libraries "]},
{"useForm":"adolescents",
"mappings": ["adolescent"]},
{"useForm":"caregivers",
"mappings": ["caregiver"]},
{"useForm":"social impacts",
"mappings": ["social impact"]},
{"useForm":"field trials",
"mappings": ["field trial"]},
{"useForm":"tailings pond",
"mappings": ["tailings ponds"]},
{"useForm":"taigas",
"mappings": ["taiga"]},
{"useForm":"consumer behaviour",
"mappings": ["consumer behavior"]},
{"useForm":"canada--politics and government--periodicals",
"mappings": ["canada--politics and government—periodicals","canada--politics and government --periodicals"]},
{"useForm":"exports--alberta",
"mappings": ["exports--alberta."]},
{"useForm":"exports--canada western",
"mappings": ["exports--canada, western."]},
{"useForm":"free trade--alberta",
"mappings": ["free trade--alberta."]},
{"useForm":"network",
"mappings": ["networks"]},
{"useForm":"playground",
"mappings": ["playgrounds"]},
{"useForm":"surface waters",
"mappings": ["surface water"]},
{"useForm":"watersheds",
"mappings": ["watershed"]},
{"useForm":"supply chain",
"mappings": ["supply chains"]},
{"useForm":"international trade",
"mappings": ["international trade."]},
{"useForm":"decision support system",
"mappings": ["decision support systems"]},
{"useForm":"forest tenure",
"mappings": ["forest tenures"]},
{"useForm":"competition",
"mappings": ["competition."]},
{"useForm":"residual trees",
"mappings": ["residual tress"]},
{"useForm":"annual reports",
"mappings": ["annual report"]},
{"useForm":"family-centered practice",
"mappings": ["family-centred practice"]},
{"useForm":"social skills interventions",
"mappings": ["social skills intervention"]},
{"useForm":"pipeline",
"mappings": ["pipelines"]},
{"useForm":"rights-of-way",
"mappings": ["right-of-way"]},
{"useForm":"pesticide",
"mappings": ["pesticides"]},
{"useForm":"alberta education",
"mappings": ["alberta education "]},
{"useForm":"autism spectrum disorder",
"mappings": ["autism spectrum disorders"]},
{"useForm":"yields",
"mappings": ["yield"]},
{"useForm":"revealed preference",
"mappings": ["revealed preferences"]},
{"useForm":"labor",
"mappings": ["labour"]},
{"useForm":"post-secondary",
"mappings": ["pose-secondary"]},
{"useForm":"environmental impact",
"mappings": ["environmental impacts"]},
{"useForm":"youth development",
"mappings": ["youth--development"]},
{"useForm":"river otter",
"mappings": ["river otters"]},
{"useForm":"agricultural land",
"mappings": ["agricultural lands"]},
{"useForm":"conservation auction",
"mappings": ["conservation auctions"]},
{"useForm":"alberta--politics and government--directories   ",
"mappings": ["alberta--politics and government--directories  "]},
{"useForm":"alberta legislative assembly--directories   ",
"mappings": ["alberta. legislative assembly--directories  "]},
{"useForm":"choice experiments",
"mappings": ["choice experiment"]},
{"useForm":"random utility models",
"mappings": ["random utility model"]},
{"useForm":"autoethnographic design",
"mappings": ["autoenthnographic design"]},
{"useForm":"consumer products",
"mappings": ["comsumer products"]},
{"useForm":"occupatonal therapy",
"mappings": ["occuptional therapy"]},
{"useForm":"sexual dysfunction",
"mappings": ["sexual dsyfunction"]},
{"useForm":"canada western--economic conditions",
"mappings": ["canada, western--economic conditions"]},
{"useForm":"occupational therapists",
"mappings": ["occupational therapist"]},
{"useForm":"exports--canada western--statistics",
"mappings": ["exports--canada, western--statistics"]},
{"useForm":"free trade--north america",
"mappings": ["free trade--north america"]},
{"useForm":"free trade--canada",
"mappings": ["free trade--canada."]},
{"useForm":"free trade--united states",
"mappings": ["free trade--united states."]},
{"useForm":"free trade--canada western",
"mappings": ["free trade--canada, western."]},
{"useForm":"small business--canada western",
"mappings": ["small business--canada, western."]},
{"useForm":"climatic changes--economic aspects",
"mappings": ["climatic changes--economic aspects"]},
{"useForm":"geopolitics",
"mappings": ["geopolitics."]},
{"useForm":"newspapers",
"mappings": ["newspaper"]},
{"useForm":"small business",
"mappings": ["small businesses"]},
{"useForm":"museum",
"mappings": ["museums"]},
{"useForm":"neighborhoods--citizen participation",
"mappings": ["neighbourhoods--citizen participation"]},
{"useForm":"constrain-induced movement therapy",
"mappings": ["constrain induce movement therapy"]},
{"useForm":"canada--parliament--periodicals",
"mappings": ["canada—parliament—periodicals", , "canada-- parliament-- periodicals",, "canada-- parliament-- periodical","canada--parliament-periodicals"]},
{"useForm":"canada--parliament--periodical",
"mappings": ["canada—parliament—periodicals", , "canada-- parliament-- periodicals",, "canada-- parliament-- periodical","canada--parliament-periodicals"]},
{"useForm":"canada--parliament-periodicals",
"mappings": ["canada—parliament—periodicals", , "canada-- parliament-- periodicals",, "canada-- parliament-- periodical","canada--parliament-periodicals"]},
{"useForm":"object oriented",
"mappings": ["object-oriented"]},
{"useForm":"health care professionals",
"mappings": ["healthcare professionals"]},
{"useForm":"social movement",
"mappings": ["social movements"]},
{"useForm":"millenials",
"mappings": ["millennials"]},
{"useForm":"consumers",
"mappings": ["consumer"]},
{"useForm":"archive",
"mappings": ["archives"]},
{"useForm":"computer mediated communication",
"mappings": ["computer-mediated communication"]},
{"useForm":"mobile device",
"mappings": ["mobile devices"]},
{"useForm":"disaster",
"mappings": ["disasters"]},
{"useForm":"motor functions",
"mappings": ["motor function"]},
{"useForm":"indigenous peoples",
"mappings": ["indigenous people"]},
{"useForm":"infants",
"mappings": ["infant"]},
{"useForm":"landscapes (photographs",
"mappings": ["landscapes (photographs)"]},
{"useForm":"behaviours",
"mappings": ["behaviors","behaviour"]},
{"useForm":"perspective",
"mappings": ["perspectives"]},
{"useForm":"learning",
"mappings": ["elearning"]},
{"useForm":"online courses",
"mappings": ["online course"]},
{"useForm":"weight-bias",
"mappings": ["weight bias"]},
{"useForm":"weight-stigma",
"mappings": ["weight stigma"]},
{"useForm":"pediatrics",
"mappings": ["pediatric"]},
{"useForm":"cochlear implant (ci)",
"mappings": ["cochlear implants (ci)"]},
{"useForm":"healthcare professional",
"mappings": ["healthcare professionals"]},
{"useForm":"data visualization ",
"mappings": ["data visualization"]},
{"useForm":"co-operatives",
"mappings": ["co-operative"]},
{"useForm":"rural and community broadband",
"mappings": ["rural and community broadband "]},
{"useForm":"cultural competence",
"mappings": ["cultural competency"]},
{"useForm":"posters",
"mappings": ["poster"]},
{"useForm":"community based",
"mappings": ["community-based"]},
{"useForm":"chemical and materials engineering",
"mappings": ["chemical and material engineering"]},
{"useForm":"sshrc",
"mappings": ["sshrc "]},
{"useForm":"information policy",
"mappings": ["information policy "]},
{"useForm":"nserc",
"mappings": ["nserc "]},
{"useForm":"discovery grant",
"mappings": ["discovery grants"]},
{"useForm":"discovery grant evaluation",
"mappings": ["discovery grants evaluation"]},
{"useForm":"nserc discovery grants",
"mappings": ["nserc discovery grant"]},
{"useForm":"research teams",
"mappings": ["research team"]},
{"useForm":"partnership grant",
"mappings": ["partnership grants"]},
{"useForm":"funding opportunity",
"mappings": ["funging opportunity"]},
{"useForm":"instructions",
"mappings": ["instructions "]},
{"useForm":"rotator cuff tears",
"mappings": ["rotator cuff tear"]},
{"useForm":"natural-disturbance",
"mappings": ["natural disturbance"]},
{"useForm":"open data",
"mappings": ["open data "]},
{"useForm":"funding opportunities",
"mappings": ["funding opportunties"]},
{"useForm":"peer review committee",
"mappings": ["peer review committees"]},
{"useForm":"budget",
"mappings": ["budgets"]},
{"useForm":"maternal infant child health research ",
"mappings": ["maternal infant child health research"]},
{"useForm":"spatialisation",
"mappings": ["spatialization"]},
{"useForm":"data management plan",
"mappings": ["data management plans"]},
{"useForm":"author disambiguation",
"mappings": ["author dissambiguation"]},
{"useForm":"nonlinear filtering",
"mappings": ["non-linear filtering"]},
{"useForm":"performing arts",
"mappings": ["performing arts  "]},
{"useForm":"acute disease",
"mappings": ["acute disease;","acutedisease"]},
{"useForm":"administration inhalation",
"mappings": ["administration, inhalation;"]},
{"useForm":"controlled clinical trials as topic",
"mappings": ["controlled clinical trials astopic"]},
{"useForm":"italy--imprints--periodicals",
"mappings": ["italy--imprints--periodicals."]},
{"useForm":"bookbinders",
"mappings": ["bookbinder"]},
{"useForm":"ion channels",
"mappings": ["ion channel"]},
{"useForm":"business enterprises--social aspects--canada--databases",
"mappings": ["business enterprises--social aspects--canada--databases"]},
{"useForm":"public opinion--alberta",
"mappings": ["public opinion -- alberta"]},
{"useForm":"redliner validation testing",
"mappings": ["readliner validation testing"]},
{"useForm":"tombak",
"mappings": ["tomak"]},
{"useForm":"alberta--social conditions--statistics",
"mappings": ["alberta -- social conditions -- statistics","alberta -- social conditions --statistics"]},
{"useForm":"social surveys--alberta",
"mappings": ["social surveys -- alberta"]},
{"useForm":"demographics",
"mappings": ["demographic"]},
{"useForm":"alberta--economic conditions--statistics",
"mappings": ["alberta -- economic conditions -- statistics","alberta -- economic conditions --statistics"]},
{"useForm":"companies",
"mappings": ["companies "]},
{"useForm":"corporate governance",
"mappings": ["corporate governance "]},
{"useForm":"executive compensation",
"mappings": ["executive compensation "]},
{"useForm":"salishan",
"mappings": ["shalishan"]},
{"useForm":"socio-demographics",
"mappings": ["sociodemographics"]},
{"useForm":"alberta economy",
"mappings": ["alberta's economy"]},
{"useForm":"companies  ",
"mappings": ["companies "]},
{"useForm":"corporate governance  ",
"mappings": ["corporate governance "]},
{"useForm":"executive compensation  ",
"mappings": ["executive compensation "]},
{"useForm":"sigo flourence",
"mappings": ["sigo, florence"]},
{"useForm":"alberta--social consitions--statistic",
"mappings": ["alberta -- social consitions -- statistics"]},
{"useForm":"neighbourhoods",
"mappings": ["neighborhoods","neighbourhood"]},
{"useForm":"statisitics",
"mappings": ["statistics.","statistics"]},
{"useForm":"victimization",
"mappings": ["vicimization"]},
{"useForm":"palliative care",
"mappings": ["pallative care"]},
{"useForm":"sshrc grant",
"mappings": ["sshrc grants"]},
{"useForm":"project grant",
"mappings": ["project grant "]},
{"useForm":"foundation grant",
"mappings": ["foundation grant "]},
{"useForm":"successful sshrc",
"mappings": ["successful sshrc "]},
{"useForm":"history",
"mappings": ["history "]},
{"useForm":"anthropocene",
"mappings": ["anthropocene "]},
{"useForm":"reclamation of land alberta",
"mappings": ["reclamation of land--alberta"]},
{"useForm":"connection grant",
"mappings": ["connection grants"]},
{"useForm":"conference",
"mappings": ["conferences"]},
{"useForm":"grants",
"mappings": ["grant"]},
{"useForm":"influenza vaccinations",
"mappings": ["influenza vaccination"]},
{"useForm":"vaccinations",
"mappings": ["vaccination"]},
{"useForm":"mental health",
"mappings": ["mental-health"]},
{"useForm":"pregnancy",
"mappings": ["pregancy"]},
{"useForm":"image analysis",
"mappings": ["imagery analysis"]},
{"useForm":"thin-layer chromatography",
"mappings": ["thin layer chromatography."]},
{"useForm":"digital ",
"mappings": ["digital"]},
{"useForm":"project",
"mappings": ["project "]},
{"useForm":"post­secondary education",
"mappings": ["postsecondary education"]},
{"useForm":"cihr update",
"mappings": ["cihr updates"]},
{"useForm":"health system services",
"mappings": ["health systems services"]},
{"useForm":"social cutural environmental and population health",
"mappings": ["social, cultural, environmental and population health"]},
{"useForm":"child ",
"mappings": ["child"]},
{"useForm":"gender",
"mappings": ["gender "]},
{"useForm":"second language acquistion",
"mappings": ["second language acquisition"]},
{"useForm":"immigrants",
"mappings": ["immigrant"]},
{"useForm":"psychometrics",
"mappings": ["psychometics"]},
{"useForm":"queer theory",
"mappings": ["queer theory "]},
{"useForm":"phenomenology ",
"mappings": ["phenomenology","phenomenology."]},
{"useForm":"urban studies ",
"mappings": ["urban studies"]},
{"useForm":"philosophy",
"mappings": ["philosophy "]},
{"useForm":"dark ecology",
"mappings": ["dark ecology "]},
{"useForm":"fine art",
"mappings": ["fine arts"]},
{"useForm":"residential schools",
"mappings": ["residential school"]},
{"useForm":"computer assisted instruction",
"mappings": ["computer assisted instruction "]},
{"useForm":"archaeology",
"mappings": ["archaeology "]},
{"useForm":"chine collé",
"mappings": ["chine collé ","chine-collé "]},
{"useForm":"collection",
"mappings": ["collection "]},
{"useForm":"consumerism",
"mappings": ["consumerism "]},
{"useForm":"digital print",
"mappings": ["digital print "]},
{"useForm":"found object",
"mappings": ["found object "]},
{"useForm":"photo-intaglio",
"mappings": ["photo-intaglio "]},
{"useForm":"woodcut",
"mappings": ["woodcut "]},
{"useForm":"television",
"mappings": ["televisione"]},
{"useForm":"youth",
"mappings": ["youth "]},
{"useForm":"prora ii",
"mappings": ["prora iii"]},
{"useForm":"oecuménisme  périodiques",
"mappings": ["oecuménisme périodiques"]},
{"useForm":"sport",
"mappings": ["sports"]},
{"useForm":"grant proposals",
"mappings": ["grant proposal"]},
{"useForm":"college of reviewers",
"mappings": ["college of reviewers "]},
{"useForm":"peace-building",
"mappings": ["peacebuilding"]},
{"useForm":"postconflict",
"mappings": ["post-conflict"]},
{"useForm":"portugese",
"mappings": ["portuguese"]},
{"useForm":"scientifiques",
"mappings": ["scientifique"]},
{"useForm":"scientists",
"mappings": ["scientist"]},
{"useForm":"mixed-methods",
"mappings": ["mixed method","mixed methods"]},
{"useForm":"annette messager",
"mappings": ["annette messager "]},
{"useForm":"dw winnicot",
"mappings": ["d.w. winnicot "]},
{"useForm":"transitional object",
"mappings": ["transitional object "]},
{"useForm":" extremism",
"mappings": ["extremism"]},
{"useForm":"sugars",
"mappings": ["sugar"]},
{"useForm":"cityscapes",
"mappings": ["cityscape"]},
{"useForm":"dental hygeine",
"mappings": ["dental hygiene"]},
{"useForm":"mountains",
"mappings": ["moutains"]},
{"useForm":"houses",
"mappings": ["hoses"]},
{"useForm":"interior",
"mappings": ["interiors"]},
{"useForm":"harbours",
"mappings": ["harbors"]},
{"useForm":"dogsledding",
"mappings": ["dog sledding"]},
{"useForm":"chest",
"mappings": ["chests"]},
{"useForm":"volcanic rocks",
"mappings": ["volcanic rock"]},
{"useForm":"springs",
"mappings": ["spring"]},
{"useForm":"sunrises & sunsets",
"mappings": ["sunrise & sunset"]},
{"useForm":"crates",
"mappings": ["craters"]},
{"useForm":"stone carving",
"mappings": ["stone carvings"]},
{"useForm":"handicraft",
"mappings": ["handicrafts"]},
{"useForm":"wild fruit - northern canada",
"mappings": ["wild fruit - northern canada, "]},
{"useForm":"bunch berry",
"mappings": ["bunchberry"]},
{"useForm":"medicinal plants - northern canada",
"mappings": ["medicinal plants - northern canda"]},
{"useForm":"country food - arctic regions",
"mappings": ["country foods - arctic regions"]},
{"useForm":"food sustainability - northern canda",
"mappings": ["food sustainability - northern canada"]},
{"useForm":"sculpture - inuvialuit ",
"mappings": ["sculpture - inuvialuit"]},
{"useForm":"aboriginal women",
"mappings": ["aboriginal men"]},
{"useForm":"food availability - arctic regions",
"mappings": ["food availability- arctic regions"]},
{"useForm":"food prices - arctic regions",
"mappings": ["food prices  - arctic regions"]},
{"useForm":"canadian gooseberry",
"mappings": ["canadian goosberry"]},
{"useForm":"dahgho (scs)",
"mappings": [" dahgho (scs)"]},
{"useForm":"ribes oxyacanthoides (lat)",
"mappings": [" ribes oxyacanthoides (lat)"]},
{"useForm":"ᒥᕐᖁᐊᓕᒃ (inuktitut syllabics)",
"mappings": [" ᒥᕐᖁᐊᓕᒃ (inuktitut syllabics)"]},
{"useForm":"igluqpak - pichaaq (qivu) ",
"mappings": ["igluqpak - pichaaq (qivu)"]},
{"useForm":"serum cholestrol",
"mappings": ["serum cholesterol"]},
{"useForm":"spitzbergen norway",
"mappings": ["spitsbergen, norway"]},
{"useForm":"tingmiaq - piksauyaq (ikt)",
"mappings": ["tingmiaq - piksauyaq (ikt) "]},
{"useForm":"yat’alá (xsl)  ",
"mappings": ["yat’alá (xsl)","yat’alá (xsl) "]},
{"useForm":"architectural decoration - polar regions",
"mappings": ["architectural decoration - polar  regions"]},
{"useForm":"beaded clothing - sakha republic -russia",
"mappings": ["beaded clothing - sakha republic - russia"]},
{"useForm":"iliharvik - pichaaq (qivu) ",
"mappings": ["iliharvik - pichaaq (qivu)"]},
{"useForm":"iliharvik - piksauyaq  (ikt)",
"mappings": ["iliharvik - piksauyaq (ikt)"]},
{"useForm":"ilisarvik - piksauyak (qivs)",
"mappings": [" ilisarvik - piksauyak (qivs)"]},
{"useForm":"bascilicas",
"mappings": ["basilicas"]},
{"useForm":"landscape (photographs)",
"mappings": ["landscapes (photographs)"]},
{"useForm":"nanuq - piksauyaq (ikt)",
"mappings": ["nanuq -piksauyaq (ikt)"]},
{"useForm":"amelanchier alnifolia (lat) ",
"mappings": ["amelanchier alnifolia (lat)"]},
{"useForm":"indian pear (old name) ",
"mappings": ["indian pear (old name)"]},
{"useForm":"june berries (united states name) ",
"mappings": ["june berries (united states name)"]},
{"useForm":"k'ęàjie (dene) ",
"mappings": ["k'ęàjie (dene)"]},
{"useForm":"k'eedzii (tlicho) ",
"mappings": ["k'eedzii (tlicho)"]},
{"useForm":"k’ñjíé (xsl) ",
"mappings": ["k’ñjíé (xsl)"]},
{"useForm":"ki jie (chp) ",
"mappings": ["ki jie (chp)"]},
{"useForm":"misakwatōminatik (cre) ",
"mappings": ["misakwatōminatik (cre)"]},
{"useForm":"misaskatoomena (cre) ",
"mappings": ["misaskatoomena (cre)"]},
{"useForm":"petites poires (fre) ",
"mappings": ["petites poires (fre)"]},
{"useForm":"saskwatōmin (cre) ",
"mappings": ["saskwatōmin (cre)"]},
{"useForm":"shadberries ",
"mappings": ["shadberries"]},
{"useForm":"sugar pear ",
"mappings": ["sugar pear"]},
{"useForm":"community gardens - northern canada",
"mappings": ["community gardens - northern canda"]},
{"useForm":"seabirds",
"mappings": ["sea birds"]},
{"useForm":"food sustainabiliy",
"mappings": ["food sustainability"]},
{"useForm":"road cleaning equipment - urban environment",
"mappings": ["road cleaning equipment - urban environments"]},
{"useForm":"atōsbīah (cre)",
"mappings": ["atōspīah (cre)"]},
{"useForm":"mihkwatōspi (cre)",
"mappings": ["miskwatōspi (cre)","mithkwatōspi (cre)"]},
{"useForm":"wakinakum (cre)",
"mappings": ["wakinakun (cre)"]},
{"useForm":"kavisilik (seb)",
"mappings": ["kavisilik (swb)"]},
{"useForm":"academic achievement",
"mappings": ["academic achievement"]},
{"useForm":"memory",
"mappings": ["memory"]},
{"useForm":"geochemistry",
"mappings": ["geochemistry."]},
{"useForm":"carbonates",
"mappings": ["carbonate"]},
{"useForm":"catalysis",
"mappings": ["catalysis."]},
{"useForm":"amides",
"mappings": ["amides."]},
{"useForm":"imides",
"mappings": ["imide"]},
{"useForm":"magnetic fields",
"mappings": ["magnetic field"]},
{"useForm":"ischemia",
"mappings": ["ischemia."]},
{"useForm":"counseling",
"mappings": ["counselling","counseling"]},
{"useForm":"personality",
"mappings": ["personality"]},
{"useForm":"ontology",
"mappings": ["ontology"]},
{"useForm":"platinum",
"mappings": ["platinum."]},
{"useForm":"cross-cultural studies",
"mappings": ["cross-cultural studies"]},
{"useForm":"ethics",
"mappings": ["ethics."]},
{"useForm":"marinopyrrole b",
"mappings": ["marinopyrrole"]},
{"useForm":"fermentation",
"mappings": ["fermentation"]},
{"useForm":"self-esteem",
"mappings": ["self-esteem"]},
{"useForm":"artificial intelligence",
"mappings": ["artificial intelligence."]},
{"useForm":"cooperative communication",
"mappings": ["cooperative communications"]},
{"useForm":"leadership",
"mappings": ["leadership"]},
{"useForm":"discourse analysis",
"mappings": ["discourse analysis"]},
{"useForm":"revolution",
"mappings": ["evolution"]},
{"useForm":"fibroblasts",
"mappings": ["fibroblast"]},
{"useForm":"petroleum engineering",
"mappings": ["petroleum engineering"]},
{"useForm":"bacteriocin",
"mappings": ["bacteriocins.","bacteriocins"]},
{"useForm":"lactic acid bacteria",
"mappings": ["lactic acid bacteria."]},
{"useForm":"nk cells",
"mappings": ["nk cell"]},
{"useForm":"reflexes",
"mappings": ["reflexes"]},
{"useForm":"women--psychology",
"mappings": ["men--psychology."]},
{"useForm":"intuition",
"mappings": ["intuition"]},
{"useForm":"macrophage",
"mappings": ["macrophages","macrophages."]},
{"useForm":"relaxation",
"mappings": ["relaxation"]},
{"useForm":"river",
"mappings": ["rivers"]},
{"useForm":"yeast",
"mappings": ["yeast."]},
{"useForm":"antioxidant",
"mappings": ["antioxidants","antioxidants."]},
{"useForm":"cadmium",
"mappings": ["cadmium."]},
{"useForm":"literacy",
"mappings": ["literacy."]},
{"useForm":"p-cycles",
"mappings": ["p-cycle"]},
{"useForm":"machine learning",
"mappings": ["machine learning."]},
{"useForm":"fungal diseases of plants",
"mappings": ["fungal diseases of plants."]},
{"useForm":"plant-pathogen relationships",
"mappings": ["plant-pathogen relationships."]},
{"useForm":"barley",
"mappings": ["barley."]},
{"useForm":"carbon compounds",
"mappings": ["carbonyl compounds."]},
{"useForm":"social exchange",
"mappings": ["social exchange."]},
{"useForm":"adult education",
"mappings": ["adult education."]},
{"useForm":"sterols",
"mappings": ["sterols."]},
{"useForm":"photoluminescence",
"mappings": ["photoluminescence."]},
{"useForm":"human computer interaction",
"mappings": ["human-computer interaction."]},
{"useForm":"control theory",
"mappings": ["control theory."]},
{"useForm":"feedback control systems",
"mappings": ["feedback control systems."]},
{"useForm":"reading comprehension",
"mappings": ["reading comprehension"]},
{"useForm":"grazing",
"mappings": ["grazing"]},
{"useForm":"public",
"mappings": ["publics"]},
{"useForm":"quantum dot",
"mappings": ["quantum dots"]},
{"useForm":"listening",
"mappings": ["listening"]},
{"useForm":"sediments",
"mappings": ["sediment"]},
{"useForm":"carbon",
"mappings": ["carbon."]},
{"useForm":"liquid chromatography",
"mappings": ["liquid chromatography"]},
{"useForm":"educational technology",
"mappings": ["educational technology"]},
{"useForm":"game theory",
"mappings": ["game theory"]},
{"useForm":"soil science",
"mappings": ["soil science."]},
{"useForm":"neurotrophins",
"mappings": ["neurotrophin"]},
{"useForm":"micromagnetics",
"mappings": ["micromagnetism"]},
{"useForm":"scanning tunneling microscopy",
"mappings": ["scanning tunneling microscopy."]},
{"useForm":"rats--physiology",
"mappings": ["cats--physiology."]},
{"useForm":"pharmacokinetics",
"mappings": ["pharmacokinetic","pharmacokinetics"]},
{"useForm":"streptomyces clavuligerus",
"mappings": ["streptomyces clavuligerus"]},
{"useForm":"t cells",
"mappings": ["t cells."]},
{"useForm":"moral education",
"mappings": ["moral education"]},
{"useForm":"adenosine",
"mappings": ["adenosine."]},
{"useForm":"multi-packet reception",
"mappings": ["multipacket reception"]},
{"useForm":"hepatocytes",
"mappings": ["hepatocyte"]},
{"useForm":"rhodium",
"mappings": ["rhodium."]},
{"useForm":"virtual character",
"mappings": ["virtual characters"]},
{"useForm":"parent-teacher relationships",
"mappings": ["parent-teacher relationships"]},
{"useForm":"inflammation",
"mappings": ["inflammation."]},
{"useForm":"heavy oil",
"mappings": ["heavy oils"]},
{"useForm":"tumor necrosis factor",
"mappings": ["tumor necrosis factor"]},
{"useForm":"sodium",
"mappings": ["sodium"]},
{"useForm":"barnacles",
"mappings": ["barnacles."]},
{"useForm":"crustacea",
"mappings": ["crustacean"]},
{"useForm":"obesity",
"mappings": ["obesity."]},
{"useForm":"glucose",
"mappings": ["glucose."]},
{"useForm":"insulin",
"mappings": ["insulin."]},
{"useForm":"facies modeling",
"mappings": ["facies modelling"]},
{"useForm":"oscillations",
"mappings": ["oscillation"]},
{"useForm":"architecture",
"mappings": ["achitecture"]},
{"useForm":"fiction",
"mappings": ["friction"]},
{"useForm":"space",
"mappings": ["dspace"]},
{"useForm":"solvation",
"mappings": ["solvation"]},
{"useForm":"mitochondria",
"mappings": ["mitochondria"]},
{"useForm":"feminism",
"mappings": ["feminism"]},
{"useForm":"existential psychology",
"mappings": ["existential psychology"]},
{"useForm":"perception",
"mappings": ["perception."]},
{"useForm":"lie algebras",
"mappings": ["lie algebras"]},
{"useForm":"children's literature",
"mappings": ["children's literature"]},
{"useForm":"empathy",
"mappings": ["empathy."]},
{"useForm":"mesenchymal stem cells",
"mappings": ["mesenchymal stem cell"]},
{"useForm":"co-channel interference",
"mappings": ["cochannel interference"]},
{"useForm":"semantics",
"mappings": ["semantics."]},
{"useForm":"teaching",
"mappings": ["teaching"]},
{"useForm":"diagenesis",
"mappings": ["diagenesis."]},
{"useForm":"greenhouse gas emissions",
"mappings": ["greenhouse gas emission"]},
{"useForm":"socialization",
"mappings": ["socialization."]},
{"useForm":"moral development",
"mappings": ["moral development."]},
{"useForm":"chemotherapy",
"mappings": ["chemotherapy"]},
{"useForm":"psychotherapy",
"mappings": ["psychotherapy"]},
{"useForm":"adolescence",
"mappings": ["adolescence"]},
{"useForm":"community-based participatory research",
"mappings": ["community based participatory research"]},
{"useForm":"inference",
"mappings": ["inference"]},
{"useForm":"gene therapy",
"mappings": ["gene therapy"]},
{"useForm":"herpes simplex virus",
"mappings": ["herpes simplex virus"]},
{"useForm":"representation",
"mappings": ["representational"]},
{"useForm":"locally compact group",
"mappings": ["locally compact groups","locally compact groups."]},
{"useForm":"selenium",
"mappings": ["selenium."]},
{"useForm":"multidrug resistance",
"mappings": ["multi-drug resistance"]},
{"useForm":"microsensor",
"mappings": ["micro sensor","microsensors"]},
{"useForm":"slopes (soil mechanics)",
"mappings": ["slopes (soil mechanics)."]},
{"useForm":"tomography",
"mappings": ["tomography"]},
{"useForm":"reflectance spectroscopy",
"mappings": ["reflectance spectroscopy"]},
{"useForm":"frost",
"mappings": ["frost."]},
{"useForm":"prions",
"mappings": ["prion"]},
{"useForm":"finite element analysis",
"mappings": ["finite-element-analysis"]},
{"useForm":"family",
"mappings": ["family."]},
{"useForm":"metacognition",
"mappings": ["metacognition"]},
{"useForm":"adsorption",
"mappings": ["adsorption"]},
{"useForm":"transfection",
"mappings": ["transfection."]},
{"useForm":"polymer",
"mappings": ["polymers","polymers."]},
{"useForm":"non viral gene delivery",
"mappings": ["non-viral gene delivery"]},
{"useForm":"paclitaxel",
"mappings": ["paclitaxel."]},
{"useForm":"tumor",
"mappings": ["tumour"]},
{"useForm":"mouse model",
"mappings": ["mouse models"]},
{"useForm":"oxidation",
"mappings": ["oxidation."]},
{"useForm":"popular culture",
"mappings": ["popular culture."]},
{"useForm":"american",
"mappings": ["america"]},
{"useForm":"postmodernism",
"mappings": ["postmodernism."]},
{"useForm":"spirituality",
"mappings": ["spirituality."]},
{"useForm":"graphite",
"mappings": ["graphite"]},
{"useForm":"pyrolysis",
"mappings": ["pyrolysis"]},
{"useForm":"paratext",
"mappings": ["paratexts"]},
{"useForm":"aesthetics",
"mappings": ["anesthetics.","aesthetics"]},
{"useForm":"amphetamine",
"mappings": ["amphetamines."]},
{"useForm":"imagination",
"mappings": ["imagination"]},
{"useForm":"opioids",
"mappings": ["opioids"]},
{"useForm":"solid oxide fuel cells",
"mappings": ["solid oxide fuel cell"]},
{"useForm":"action research",
"mappings": ["action research"]},
{"useForm":"child-development",
"mappings": ["child development.","child development"]},
{"useForm":"structural-equation-modeling",
"mappings": ["structural equation modeling"]},
{"useForm":"universities and colleges",
"mappings": ["universities and colleges."]},
{"useForm":"dendrite",
"mappings": ["dendrites"]},
{"useForm":"dopamine",
"mappings": ["dopamine."]},
{"useForm":"neuropeptide y",
"mappings": ["neuropeptide y."]},
{"useForm":"listeria monocytogenes",
"mappings": ["listeria monocytogenes."]},
{"useForm":"glycolipids",
"mappings": ["glycolipid"]},
{"useForm":"persistence",
"mappings": ["persistence."]},
{"useForm":"values",
"mappings": ["values","value"]},
{"useForm":"anisotropy",
"mappings": ["anisotropy."]},
{"useForm":"starch",
"mappings": ["starch"]},
{"useForm":"bread",
"mappings": ["bread"]},
{"useForm":"dough",
"mappings": ["dough"]},
{"useForm":"intrinsic motivation",
"mappings": ["intrinsic motivation"]},
{"useForm":"gas chromatography",
"mappings": ["gas chromatography."]},
{"useForm":"psycholinguistics",
"mappings": ["psycholinguistics"]},
{"useForm":"hermeneutics",
"mappings": ["hermeneutics"]},
{"useForm":"diels-alder reaction",
"mappings": ["diels-alder reactions"]},
{"useForm":"vibration",
"mappings": ["vibration."]},
{"useForm":"proanthocyanidin",
"mappings": ["proanthocyanidins"]},
{"useForm":"dementia",
"mappings": ["dementia."]},
{"useForm":"cholesterol",
"mappings": ["cholesterol."]},
{"useForm":"neurons",
"mappings": ["neurons."]},
{"useForm":"rodent",
"mappings": ["rodents"]},
{"useForm":"hydrocarbons",
"mappings": ["hydrocarbon"]},
{"useForm":"liquids",
"mappings": ["liquids."]},
{"useForm":"attitudes",
"mappings": ["attitude"]},
{"useForm":"morality",
"mappings": ["orality"]},
{"useForm":"frozen ground",
"mappings": ["frozen ground."]},
{"useForm":"fault detection",
"mappings": ["fault-detection"]},
{"useForm":"robots",
"mappings": ["roots"]},
{"useForm":"memory disorders in old age",
"mappings": ["memory disorders--in old age."]},
{"useForm":"viscoelasticity",
"mappings": ["viscoelasticity"]},
{"useForm":"carbohydrates",
"mappings": ["carbohydrates","carbohydrate"]},
{"useForm":"wounds healing",
"mappings": ["wound healing."]},
{"useForm":"democracy",
"mappings": ["democracy"]},
{"useForm":"time-series analysis",
"mappings": ["time series analysis"]},
{"useForm":"conformational analysis",
"mappings": ["conformational analysis"]},
{"useForm":"ran interference",
"mappings": ["rna interference"]},
{"useForm":"liver",
"mappings": ["liver."]},
{"useForm":"total synthesis",
"mappings": ["total sythesis"]},
{"useForm":"radiotherapy",
"mappings": ["radiotherapy."]},
{"useForm":"magnetic resonance imaging",
"mappings": ["magnetic resonance imaging."]},
{"useForm":"tensor",
"mappings": ["tensors"]},
{"useForm":"serine proteinases",
"mappings": ["serine proteases"]},
{"useForm":"peptide",
"mappings": ["peptides"]},
{"useForm":"biological transport",
"mappings": ["biological transport"]},
{"useForm":"exercise",
"mappings": ["exercise."]},
{"useForm":"cryobiology",
"mappings": ["cryobiology"]},
{"useForm":"linac-mr",
"mappings": ["linac-mri"]},
{"useForm":"finite element method",
"mappings": ["finite element method."]},
{"useForm":"linguistics",
"mappings": ["linguistics"]},
{"useForm":"swine--nutrition",
"mappings": ["swine -- nutrition"]},
{"useForm":"judgment",
"mappings": ["judgment"]},
{"useForm":"allelopathy",
"mappings": ["allelopathy"]},
{"useForm":"governance",
"mappings": ["governace"]},
{"useForm":"candida",
"mappings": ["candida."]},
{"useForm":"buried pipeline",
"mappings": ["buried pipelines"]},
{"useForm":"eighteenth century",
"mappings": ["eighteenth-century"]},
{"useForm":"uncertainty",
"mappings": ["uncertainty."]},
{"useForm":"erbium",
"mappings": ["terbium"]},
{"useForm":"apoptosis",
"mappings": ["apoptosis."]},
{"useForm":"power systems",
"mappings": ["power system"]},
{"useForm":"carbon-nanotube",
"mappings": ["carbon nanotube","carbon nanotubes"]},
{"useForm":"field-effect transistor",
"mappings": ["field-effect transistors."]},
{"useForm":"scoliosis",
"mappings": ["scoliosis"]},
{"useForm":"haunting",
"mappings": ["hauntings"]},
{"useForm":"post-secondary education",
"mappings": ["postsecondary education"]},
{"useForm":"langmuir probes",
"mappings": ["langmuir probe"]},
{"useForm":"calcium",
"mappings": ["calcium"]},
{"useForm":"laminar flow",
"mappings": ["laminar flow"]},
{"useForm":"mass transfer",
"mappings": ["mass transfer"]},
{"useForm":"distributed parameter system",
"mappings": ["distributed parameter systems"]},
{"useForm":"poplar",
"mappings": ["polar"]},
{"useForm":"soft sensor",
"mappings": ["soft senor"]},
{"useForm":"christian education",
"mappings": ["christian education"]},
{"useForm":"oligomers",
"mappings": ["oligomer"]},
{"useForm":"information retrieval",
"mappings": ["information retrieval."]},
{"useForm":"transcription factors",
"mappings": ["transcription factor"]},
{"useForm":"alignment",
"mappings": ["alignments"]},
{"useForm":"environmental health",
"mappings": ["environmental health."]},
{"useForm":"masculinity",
"mappings": ["masculinity."]},
{"useForm":"amphotericin b",
"mappings": ["amphotericin b."]},
{"useForm":"management",
"mappings": ["management."]},
{"useForm":"women",
"mappings": ["women"]},
{"useForm":"psychoanalysis",
"mappings": ["psychoanalysis"]},
{"useForm":"thin films",
"mappings": ["thin films","thin film"]},
{"useForm":"subjectivitiy",
"mappings": ["subjectivity"]},
{"useForm":"russian",
"mappings": ["russia"]},
{"useForm":"artifacts",
"mappings": ["artifact"]},
{"useForm":"phylogeography",
"mappings": ["phytogeography"]},
{"useForm":"bitumen",
"mappings": ["bitumen."]},
{"useForm":"solvent extraction",
"mappings": ["solvent extraction."]},
{"useForm":"item response theory",
"mappings": ["item response theory."]},
{"useForm":"hydrogen bonding",
"mappings": ["hydrogen bonding."]},
{"useForm":"genetic algorithm",
"mappings": ["genetic algorithms.","genetic algorithms"]},
{"useForm":"psychologists",
"mappings": ["psychologists."]},
{"useForm":"blame",
"mappings": ["blame."]},
{"useForm":"isotope labeling",
"mappings": ["isotope labelling"]},
{"useForm":"finite element",
"mappings": ["finite elements"]},
{"useForm":"fracture",
"mappings": ["fractured"]},
{"useForm":"marinopyrroles",
"mappings": ["marinopyrrole"]},
{"useForm":"lipids",
"mappings": ["lipids"]},
{"useForm":"intersubjectivity",
"mappings": ["intersubjectivity"]},
{"useForm":"sensor",
"mappings": ["sensory"]},
{"useForm":"organizational change",
"mappings": ["organizational change"]},
{"useForm":"phylogeny",
"mappings": ["phylogeny."]},
{"useForm":"two-component system",
"mappings": ["two component system"]},
{"useForm":"actor network theory",
"mappings": ["actor-network theory"]},
{"useForm":"corrosion fatigue",
"mappings": ["corrosion-fatigue"]},
{"useForm":"pipeline steels",
"mappings": ["pipeline steel"]},
{"useForm":"edge effect",
"mappings": ["edge effects"]},
{"useForm":"thermodynamics",
"mappings": ["thermodynamics"]},
{"useForm":"protein kinase c",
"mappings": ["protein-kinase-c","protein kinase a"]},
{"useForm":"noradrenaline",
"mappings": ["noradrenaline"]},
{"useForm":"image processing",
"mappings": ["image processing"]},
{"useForm":"computer vision",
"mappings": ["computer vision"]},
{"useForm":"approximation algorithms",
"mappings": ["approximation algorithm"]},
{"useForm":"cost-effectiveness",
"mappings": ["cost effectiveness."]},
{"useForm":"cell cycle",
"mappings": ["cell cycle."]},
{"useForm":"motor learning",
"mappings": ["motor learning"]},
{"useForm":"corporate culture",
"mappings": ["corporate culture"]},
{"useForm":"gangliosides",
"mappings": ["ganglioside"]},
{"useForm":"nucleoside",
"mappings": ["nucleosides."]},
{"useForm":"wheat",
"mappings": ["wheat."]},
{"useForm":"sympathetic nervous system",
"mappings": ["sympathetic nervous system"]},
{"useForm":"language arts",
"mappings": ["language arts"]},
{"useForm":"nanostructure",
"mappings": ["nanostructures"]},
{"useForm":"drosophila melanogaster",
"mappings": ["drosophila melanogaster."]},
{"useForm":"motherhood",
"mappings": ["motherhood"]},
{"useForm":"educational policy",
"mappings": ["education policy"]},
{"useForm":"gender identity",
"mappings": ["gender identity"]},
{"useForm":"learning disabilities",
"mappings": ["learning disabilities"]},
{"useForm":"forecasting",
"mappings": ["forecasting."]},
{"useForm":"micro-structure",
"mappings": ["microstructure"]},
{"useForm":"water chemistry",
"mappings": ["water chemistry"]},
{"useForm":"cyclosporine",
"mappings": ["cyclosporine"]},
{"useForm":"smoking",
"mappings": ["smoking"]},
{"useForm":"psychiatric nursing",
"mappings": ["psychiatric nursing"]},
{"useForm":"multi-hop",
"mappings": ["multihop"]},
{"useForm":"multi-agent systems",
"mappings": ["multiagent systems"]},
{"useForm":"sampled data control",
"mappings": ["sampled-data control"]},
{"useForm":"thin layer chromatography",
"mappings": ["thin layer chromatography.","thin-layer chromatography"]},
{"useForm":"diaspore",
"mappings": ["diaspores"]},
{"useForm":"athecate hydroids",
"mappings": ["thecate hydroids."]},
{"useForm":"cytotoxic t lymphocytes",
"mappings": ["cytotoxic t lymphocyte"]},
{"useForm":"conflicts",
"mappings": ["conflict"]},
{"useForm":"palaeontology",
"mappings": ["paleontology"]},
{"useForm":"older adults",
"mappings": ["older adult"]},
{"useForm":"hydrogen sulfide",
"mappings": ["hydrogen sulfide."]},
{"useForm":"crystallization",
"mappings": ["crystallization"]},
{"useForm":"dispersion",
"mappings": ["dispersion"]},
{"useForm":"phospholipids",
"mappings": ["phospholipids"]},
{"useForm":"liposomes",
"mappings": ["liposomes","liposome"]},
{"useForm":"anesthetics",
"mappings": ["aesthetics"]},
{"useForm":"antidepressants",
"mappings": ["antidepressants"]},
{"useForm":"auditing",
"mappings": ["auditing"]},
{"useForm":"hypergroup",
"mappings": ["hypergroups"]},
{"useForm":"self assembly",
"mappings": ["self-assembly"]},
{"useForm":"autism",
"mappings": ["autism."]},
{"useForm":"nursing education",
"mappings": ["nursing educatiion"]},
{"useForm":"connection",
"mappings": ["connections"]},
{"useForm":"motivation",
"mappings": ["motivation.","motivations"]},
{"useForm":"ligands",
"mappings": ["ligand"]},
{"useForm":"glaciology",
"mappings": ["glaciology."]},
{"useForm":"multiscale modeling",
"mappings": ["multi-scale modelling"]},
{"useForm":"hydraulic fracturing",
"mappings": ["hydraulic fracturing."]},
{"useForm":"altruism",
"mappings": ["altruism"]},
{"useForm":"hepatitis c virus",
"mappings": ["hepatitis b virus","hepatitis b virus."]},
{"useForm":"family caregiver",
"mappings": ["family caregivers"]},
{"useForm":"human capital",
"mappings": ["human capital."]},
{"useForm":"multiple sclerosis",
"mappings": ["mulitple sclerosis"]},
{"useForm":"placenta",
"mappings": ["placenta"]},
{"useForm":"acculturation",
"mappings": ["acculturation."]},
{"useForm":"risk assessmen",
"mappings": ["risk assessment","risk assessment."]},
{"useForm":"affordances",
"mappings": ["affordance"]},
{"useForm":"stochastic gradient-descent",
"mappings": ["stochastic gradient descent"]},
{"useForm":"information behaviour",
"mappings": ["information behaviours"]},
{"useForm":"phosphatases",
"mappings": ["phosphatases"]},
{"useForm":"enzyme inhibitors",
"mappings": ["enzyme inhibitors"]},
{"useForm":"translation",
"mappings": ["translations"]},
{"useForm":"literature",
"mappings": ["literature."]},
{"useForm":"social influence",
"mappings": ["social influence."]},
{"useForm":"red blood cell",
"mappings": ["red blood cells"]},
{"useForm":"markov chains",
"mappings": ["markov chain"]},
{"useForm":"infinite dimensional systems",
"mappings": ["infinite-dimensional systems"]},
{"useForm":"arts-based research",
"mappings": ["arts based research"]},
{"useForm":"swine--feeding and feeds",
"mappings": ["swine -- feeding and feeds"]},
{"useForm":"natural product",
"mappings": ["natural products."]},
{"useForm":"melanoma",
"mappings": ["melanoma."]},
{"useForm":"surfactant",
"mappings": ["surfactants"]},
{"useForm":"new media",
"mappings": ["news media"]},
{"useForm":"humanism",
"mappings": ["humanism."]},
{"useForm":"sulfides",
"mappings": ["sulfide"]},
{"useForm":"anxiety",
"mappings": ["anxiety"]},
{"useForm":"interferon",
"mappings": ["interferon"]},
{"useForm":"acute myeloid leukemia",
"mappings": ["acute myeloid leukemia"]},
{"useForm":"cell membranes",
"mappings": ["cell membrane"]},
{"useForm":"autoimmunity",
"mappings": ["autoimmunity"]},
{"useForm":"canola oil",
"mappings": ["canola oil"]},
{"useForm":"organic photovoltaic",
"mappings": ["organic photovoltaics"]},
{"useForm":"myocardium",
"mappings": ["myocardium"]},
{"useForm":"block copolymer",
"mappings": ["block copolymers"]},
{"useForm":"on-site wastewater treatment system",
"mappings": ["onsite wastewater treatment system"]},
{"useForm":"computational linguistics",
"mappings": ["computational linguistics."]},
{"useForm":"polychlorinated biphenyl",
"mappings": ["polychlorinated biphenyls"]},
{"useForm":"historical linguistics",
"mappings": ["historical linguistics."]},
{"useForm":"critical theory",
"mappings": ["critical theory."]},
{"useForm":"opioid",
"mappings": ["opioids"]},
{"useForm":"methylxanthine",
"mappings": ["methylxanthines"]},
{"useForm":"theophylline",
"mappings": ["theophylline."]},
{"useForm":"image",
"mappings": ["images"]},
{"useForm":"asthma",
"mappings": ["asthma."]},
{"useForm":"bioacoustics",
"mappings": ["bioacoustic"]},
{"useForm":"preservice teachers",
"mappings": ["pre-service teacher"]},
{"useForm":"ideology",
"mappings": ["ideology."]},
{"useForm":"pharmacodynamic",
"mappings": ["pharmacodynamics"]},
{"useForm":"boundary layers",
"mappings": ["boundary layer","boundary layer."]},
{"useForm":"urbanization",
"mappings": ["urbanization"]},
{"useForm":"heart",
"mappings": ["heart."]},
{"useForm":"energy metabolism",
"mappings": ["energy metabolism."]},
{"useForm":"alk+ alcl",
"mappings": ["alk+alcl"]},
{"useForm":"nanotubes",
"mappings": ["nanotube"]},
{"useForm":"enzyme kinetics",
"mappings": ["enzyme kinetics."]},
{"useForm":"emotions",
"mappings": ["emotions","emotion"]},
{"useForm":"cognition",
"mappings": ["cognition."]},
{"useForm":"liminality",
"mappings": ["liminality."]},
{"useForm":"brassica napus",
"mappings": ["brassia napus"]},
{"useForm":"auxin",
"mappings": ["auxin."]},
{"useForm":"random walks",
"mappings": ["random walk"]},
{"useForm":"reading",
"mappings": ["reading."]},
{"useForm":"families",
"mappings": ["families."]},
{"useForm":"amino acids",
"mappings": ["amino acid","amino acids"]},
{"useForm":"tillage",
"mappings": ["tillage."]},
{"useForm":"refugee",
"mappings": ["refugees","refugee"]},
{"useForm":"cytoskeleton",
"mappings": ["cytoskeleton."]},
{"useForm":"lactose",
"mappings": ["lactose."]},
{"useForm":"nano-filtration",
"mappings": ["nanofiltration"]},
{"useForm":"stable isotope",
"mappings": ["stable isotopes"]},
{"useForm":"strictly singular operator",
"mappings": ["strictly singular operators"]},
{"useForm":"requirement",
"mappings": ["requirements"]},
{"useForm":"resin",
"mappings": ["resine"]},
{"useForm":"protein binding",
"mappings": ["protein binding"]},
{"useForm":"realism",
"mappings": ["realism"]},
{"useForm":"concrete walls--design and construction",
"mappings": ["concrete walls--design and construction"]},
{"useForm":"vocational education",
"mappings": ["vocational education."]},
{"useForm":"chromatin remodelling",
"mappings": ["chromatin remodeling"]},
{"useForm":"language acquisition",
"mappings": ["language acquisition"]},
{"useForm":"bilingualism",
"mappings": ["bilingualism"]},
{"useForm":"nucleic acid",
"mappings": ["nucleic acids.","nucleic acids"]},
{"useForm":"caching",
"mappings": ["catching"]},
{"useForm":"polymeric micelle",
"mappings": ["polymer micelle","polymeric micelles"]},
{"useForm":"graph theory",
"mappings": ["graph theory."]},
{"useForm":"touch",
"mappings": ["touch"]},
{"useForm":"biosynthesis",
"mappings": ["biosynthesis"]},
{"useForm":"artificial neural networks",
"mappings": ["artificial neural network"]},
{"useForm":"banach spaces",
"mappings": ["banach spaces."]},
{"useForm":"brain",
"mappings": ["brain"]},
{"useForm":"potassium channels",
"mappings": ["potassium channels."]},
{"useForm":"developmental disabilities",
"mappings": ["developmental disabilities."]},
{"useForm":"membrane proteins",
"mappings": ["membrane protein"]},
{"useForm":"aphasia",
"mappings": ["aphasia."]},
{"useForm":"sociology",
"mappings": ["sociology"]},
{"useForm":"nanomaterials",
"mappings": ["nanomaterial"]},
{"useForm":"victorians",
"mappings": ["victorian"]},
{"useForm":"chronic pain",
"mappings": ["chronic pain."]},
{"useForm":"student teachers",
"mappings": ["student-teachers"]},
{"useForm":"muscle contraction",
"mappings": ["muscle contraction."]},
{"useForm":"structural stability",
"mappings": ["structural stability."]},
{"useForm":"tibialis anterior muscle",
"mappings": ["tibialis anterior muscle"]},
{"useForm":"self-weight consolidation",
"mappings": ["self weight consolidation"]},
{"useForm":"spectrometry",
"mappings": ["spectrometry","spectometry"]},
{"useForm":"interpolation",
"mappings": ["interpolation."]},
{"useForm":"wavelets",
"mappings": ["wavelet"]},
{"useForm":"nanocomposite",
"mappings": ["nanocomposites","nanocmposite"]},
{"useForm":"schizophrenia",
"mappings": ["schizophrenia"]},
{"useForm":"english language--study and teaching--foreign speakers",
"mappings": ["english language -- study and teaching -- foreign speakers"]},
{"useForm":"critical pedagogy",
"mappings": ["critical pedagogy"]},
{"useForm":"change",
"mappings": ["change."]},
{"useForm":"postcolonial",
"mappings": ["post-colonial"]},
{"useForm":"tailings (metallurgy)",
"mappings": ["tailings (metallurgy)"]},
{"useForm":"equlization",
"mappings": ["equalization"]},
{"useForm":"multiple input multiple output (mimo)",
"mappings": ["multiple-input multiple-output (mimo)"]},
{"useForm":"world wide web",
"mappings": ["world wide web"]},
{"useForm":"tunnels",
"mappings": ["tunnels"]},
{"useForm":"steroid hormones",
"mappings": ["steroid hormone"]},
{"useForm":"finance",
"mappings": ["finance"]},
{"useForm":"outdoor education",
"mappings": ["outdoor education"]},
{"useForm":"electromyography",
"mappings": ["electromyography"]},
{"useForm":"gesture",
"mappings": ["gestures"]},
{"useForm":"consciousness",
"mappings": ["consciousness"]},
{"useForm":"self-control",
"mappings": ["self-control."]},
{"useForm":"thuricin",
"mappings": ["thurincin"]},
{"useForm":"social justice",
"mappings": ["social justice"]},
{"useForm":"speculation",
"mappings": ["speculation"]},
{"useForm":"strain rate",
"mappings": ["strain-rate"]},
{"useForm":"photochemistry",
"mappings": ["photochemistry"]},
{"useForm":"organometallic",
"mappings": ["organometalics"]},
{"useForm":"relationships",
"mappings": ["relationship"]},
{"useForm":"lipid",
"mappings": ["lipids"]},
{"useForm":"hydrodynamics",
"mappings": ["hydrodynamic","hydrodynamics."]},
{"useForm":"astrophysics",
"mappings": ["astrophysics."]},
{"useForm":"lake sediment",
"mappings": ["lake sediments"]},
{"useForm":"peroxisome",
"mappings": ["peroxisomes.","peroxisomes"]},
{"useForm":"power electronics",
"mappings": ["power electronics"]},
{"useForm":"petrology",
"mappings": ["petrology."]},
{"useForm":"lipase",
"mappings": ["lipase."]},
{"useForm":"very low density lipoprotein",
"mappings": ["very-low density lipoprotein"]},
{"useForm":"eating disorders",
"mappings": ["eating disorders"]},
{"useForm":"computer",
"mappings": ["computers"]},
{"useForm":"friendship",
"mappings": ["friendship"]},
{"useForm":"entropy",
"mappings": ["entropy."]},
{"useForm":"electronics",
"mappings": ["electronics"]},
{"useForm":"korean",
"mappings": ["korea"]},
{"useForm":"healthcare teams",
"mappings": ["health care teams."]},
{"useForm":"local government",
"mappings": ["local government"]},
{"useForm":"anorexia nervosa",
"mappings": ["anorexia nervosa."]},
{"useForm":"emotion focused therapy",
"mappings": ["emotion-focused therapy"]},
{"useForm":"protein tyrosine kinase",
"mappings": ["protein-tyrosine kinase."]},
{"useForm":"palaeolithic archaeology",
"mappings": ["paleolithic archaeology"]},
{"useForm":"information theory",
"mappings": ["information theory"]},
{"useForm":"dendritic cells",
"mappings": ["dendritic cells."]},
{"useForm":"tissue-engineering",
"mappings": ["tissue engineering"]},
{"useForm":"hematopoiesis",
"mappings": ["hematopoiesis"]},
{"useForm":"mistakes",
"mappings": ["mistake"]},
{"useForm":"multivariate analysis",
"mappings": ["multivariate analysis."]},
{"useForm":"serotonin",
"mappings": ["serotonin."]},
{"useForm":"peroxidase",
"mappings": ["peroxidase."]},
{"useForm":"microencapsulation",
"mappings": ["microencapsulation"]},
{"useForm":"glycoproteins",
"mappings": ["glycoproteins."]},
{"useForm":"identity making",
"mappings": ["identity-making"]},
{"useForm":"protein-dna binding",
"mappings": ["protein-rna binding"]},
{"useForm":"conifers",
"mappings": ["conifer"]},
{"useForm":"microelectronics",
"mappings": ["microelectronics."]},
{"useForm":"fracture mechanics",
"mappings": ["fracture mechanics"]},
{"useForm":"succinate dehydrogenase",
"mappings": ["succinate dehydrogenase"]},
{"useForm":"ecology--alberta",
"mappings": ["geology--alberta."]},
{"useForm":"lipopolysaccharide",
"mappings": ["lipopoysaccharides"]},
{"useForm":"gram-negative bacteria",
"mappings": ["gram-negative bacteria"]},
{"useForm":"palaeoclimate",
"mappings": ["paleoclimate"]},
{"useForm":"ashpaltenes",
"mappings": ["ashaltenes"]},
{"useForm":"policy making",
"mappings": ["policymaking"]},
{"useForm":"metal oxides",
"mappings": ["metal oxide"]},
{"useForm":"north america",
"mappings": ["north americans"]},
{"useForm":"computational fluid dynamics",
"mappings": ["computational fluid dynamics"]},
{"useForm":"sedimentary rocks",
"mappings": ["sedimentary rocks"]},
{"useForm":"bilinear modeling",
"mappings": ["linear modeling"]},
{"useForm":"palaestra",
"mappings": ["palaestrae"]},
{"useForm":"hunter-gatherer",
"mappings": ["hunter-gatherers"]},
{"useForm":"career changes",
"mappings": ["career change"]},
{"useForm":"number theory",
"mappings": ["number theory."]},
{"useForm":"species distribution model",
"mappings": ["species distribution models"]},
{"useForm":"representationalism",
"mappings": ["representationalist"]},
{"useForm":"polyketides",
"mappings": ["polyketide"]},
{"useForm":"atmosphere",
"mappings": ["atmosphere."]},
{"useForm":"adverse events",
"mappings": ["adverse event"]},
{"useForm":"somatostatin",
"mappings": ["somatostatin"]},
{"useForm":"alkynes",
"mappings": ["alkyne"]},
{"useForm":"micro-grid",
"mappings": ["microgrid"]},
{"useForm":"nanostructured materials",
"mappings": ["nano structured materials"]},
{"useForm":"photonic crystal",
"mappings": ["photonic crystals"]},
{"useForm":"ethnomethodology",
"mappings": ["ethnomethodology."]},
{"useForm":"aspirational cite",
"mappings": ["aspirational city"]},
{"useForm":"opitcal tweezers",
"mappings": ["optical tweezers"]},
{"useForm":"prion disease",
"mappings": ["prion diseases"]},
{"useForm":"nuclear magnetic resonance",
"mappings": ["nuclear magnetic resonance."]},
{"useForm":"phosphorane imide",
"mappings": ["phosphoranimide"]},
{"useForm":"sensorimotor integration",
"mappings": ["sensorimotor integration"]},
{"useForm":"neurospora",
"mappings": ["neurospora."]},
{"useForm":"hydrogels",
"mappings": ["hydrogel"]},
{"useForm":"migration policy",
"mappings": ["immigration policy"]},
{"useForm":"extracellular matrix",
"mappings": ["extracellular matrix."]},
{"useForm":"quantum field theory",
"mappings": ["quantum field theory."]},
{"useForm":"naturally fractured reservoir",
"mappings": ["naturally fractured reservoirs"]},
{"useForm":"fetal alcohol syndrome",
"mappings": ["fetal alcohol syndrome"]},
{"useForm":"self-presentation",
"mappings": ["self-representation"]},
{"useForm":"optical fibers",
"mappings": ["optical fibers"]},
{"useForm":"synchronization",
"mappings": ["asynchronization"]},
{"useForm":"anorexia",
"mappings": ["anorexia"]},
{"useForm":"neuroplasticity",
"mappings": ["neuroplasticity"]},
{"useForm":"early childhood education",
"mappings": ["early childhood education"]},
{"useForm":"vowels",
"mappings": ["vowels"]},
{"useForm":"cosmology",
"mappings": ["cosmology"]},
{"useForm":"vertebrate palaeontology",
"mappings": ["vertebrate paleontology"]},
{"useForm":"spliceosome",
"mappings": ["spliceosomes"]},
{"useForm":"interface cracks",
"mappings": ["interface crack"]},
{"useForm":"semiotics",
"mappings": ["semiotics."]},
{"useForm":"molecular beacon",
"mappings": ["molecular beacons"]},
{"useForm":"critical humor studies",
"mappings": ["critical humour studies"]},
{"useForm":"persian humor",
"mappings": ["persian humour"]},
{"useForm":"beta-glucan",
"mappings": ["beta glucan"]},
{"useForm":"historiography",
"mappings": ["historiography."]},
{"useForm":"boosted regression tree",
"mappings": ["boosted regression trees"]},
{"useForm":"transporters",
"mappings": ["transporter"]},
{"useForm":"fluorescent protein",
"mappings": ["fluorescent proteins"]},
{"useForm":"biosensor",
"mappings": ["biosensors"]},
{"useForm":"freshwater fishes",
"mappings": ["freshwater fish"]},
{"useForm":"monte carlo tree search",
"mappings": ["monte-carlo tree search"]},
{"useForm":"heuristic",
"mappings": ["heuristics"]},
{"useForm":"meaning-making",
"mappings": ["meaning making"]},
{"useForm":"phosphorylation",
"mappings": ["dephosphorylation"]},
{"useForm":"amphibian",
"mappings": ["amphibians"]},
{"useForm":"non-expansive mappings",
"mappings": ["non-expansive mapping"]},
{"useForm":"nanowires",
"mappings": ["nanowire"]},
{"useForm":"prophet",
"mappings": ["prophets"]},
{"useForm":"teleconnections",
"mappings": ["teleconnection"]},
{"useForm":"parkinson's disease",
"mappings": ["parkinson disease"]},
{"useForm":"emulsion",
"mappings": ["emulsions"]},
{"useForm":"drill hole spacing",
"mappings": ["drillhole spacing"]},
{"useForm":"video game",
"mappings": ["videogame"]},
{"useForm":"inhibitors",
"mappings": ["inhibitor"]},
{"useForm":"group von neumann algebras",
"mappings": ["group von neumann algebra"]},
{"useForm":"motion",
"mappings": ["emotion"]},
{"useForm":"smart home",
"mappings": ["smart homes"]},
{"useForm":"solvent extractions",
"mappings": ["solvent extraction.","solvent extraction"]},
{"useForm":"transition time",
"mappings": ["transition times"]},
{"useForm":"iron transport",
"mappings": ["ion transport"]},
{"useForm":"concussion",
"mappings": ["concussions"]},
{"useForm":"parent",
"mappings": ["parents"]},
{"useForm":"wireless communication",
"mappings": ["wireless communications"]},
{"useForm":"mummers",
"mappings": ["mummer"]},
{"useForm":"mummer's play",
"mappings": ["mummers play"]},
{"useForm":"spherical harmonics",
"mappings": ["spherical h-harmonics"]},
{"useForm":"interpretative phenomenological analysis",
"mappings": ["interpretative phenomenological analyis"]},
{"useForm":"biomarkers",
"mappings": ["biomarker"]},
{"useForm":"techno-economics",
"mappings": ["techno-economic"]},
{"useForm":"controls",
"mappings": ["control"]},
{"useForm":"microtubule",
"mappings": ["microtubules"]},
{"useForm":"eye-tracking",
"mappings": ["eyetracking"]},
{"useForm":"biofilms",
"mappings": ["biofilm"]},
{"useForm":"dairy cows",
"mappings": ["dairy cow"]},
{"useForm":"centrifuge modeling",
"mappings": ["centrifuge modelling"]},
{"useForm":"bimetallic catalyst",
"mappings": ["bimetallic catalysts"]},
{"useForm":"yangian",
"mappings": ["yangians"]},
{"useForm":"microfluidics",
"mappings": ["microfluidic"]},
{"useForm":"accountability",
"mappings": ["accoutability"]},
{"useForm":"life cycle assessment",
"mappings": ["life-cycle assessment"]},
{"useForm":"big data",
"mappings": ["bigdata"]},
{"useForm":"recommender system",
"mappings": ["recommender systems"]},
{"useForm":"cancer stem cells",
"mappings": ["cancer stem cell"]},
{"useForm":"focus groups",
"mappings": ["focus group"]},
{"useForm":"high-dimensional data",
"mappings": ["high dimensional data"]},
{"useForm":"co-kriging",
"mappings": ["cokriging"]},
{"useForm":"enzymes",
"mappings": ["enzyme"]},
{"useForm":"multi-state system",
"mappings": ["multistate system"]},
{"useForm":"bioactive film",
"mappings": ["bioactive films"]},
{"useForm":"phenolic acid",
"mappings": ["phenolic acids"]},
{"useForm":"long-wave infrared",
"mappings": ["longwave infrared"]},
{"useForm":"kidney",
"mappings": ["kidneys"]},
{"useForm":"scandal",
"mappings": ["scandale"]},
{"useForm":"black hole",
"mappings": ["black holes"]},
{"useForm":"kinetics",
"mappings": ["kinetic"]},
{"useForm":"code switching",
"mappings": ["code-switching"]},
{"useForm":"south korea",
"mappings": ["south korean"]},
{"useForm":"developmentalism",
"mappings": ["developmentalist"]},
{"useForm":"manganites",
"mappings": ["manganite"]},
{"useForm":"international exposition",
"mappings": ["international expositions"]},
{"useForm":"robust designs",
"mappings": ["robust design"]},
{"useForm":"wireless sensor networks",
"mappings": ["wireless sensor network"]},
{"useForm":"optoelectronic",
"mappings": ["optoelectronics"]},
{"useForm":"archaean",
"mappings": ["archean"]},
{"useForm":"hypertrophic scars",
"mappings": ["hypertrophic scar"]},
{"useForm":"polysaccharides",
"mappings": ["polysaccharide"]},
{"useForm":"bicyclic peptides",
"mappings": ["cyclic peptides"]},
{"useForm":"time dependent density functional theory",
"mappings": ["time-dependent density functional theory"]},
{"useForm":"demulsification",
"mappings": ["emulsification"]},
{"useForm":"semiconductors",
"mappings": ["semiconductor"]},
{"useForm":"acinetobacter baumannii",
"mappings": ["acinetobacter baumanii"]},
{"useForm":"inorganic fouling",
"mappings": ["organic fouling"]},
{"useForm":"pillow",
"mappings": ["pillows"]},
{"useForm":"constructionism",
"mappings": ["constructions"]},
{"useForm":"steam assisted gravity drainage",
"mappings": ["steam-assisted gravity drainage"]},
{"useForm":"chronicles",
"mappings": ["chronicle"]},
{"useForm":"neighborhood",
"mappings": ["neighborhoods","neighbourhood"]},
{"useForm":"lantibiotic",
"mappings": ["antibiotic"]},
{"useForm":"dynamic",
"mappings": ["dynamics"]},
{"useForm":"intermolecular",
"mappings": ["intramolecular"]},
{"useForm":"concrete slabs--design and construction",
"mappings": ["concrete slabs--design and construction."]},
